### PR TITLE
add separate colors sketch library with name colors in palette and shared styles

### PR DESCRIPTION
**Pull request by estevesd**
#### Changes proposed in this pull request:
Add new Sketch Library for colors. 
Colors are named according to the variables defined in `@blueprint/core`.
Colors are available in the palette as well as in shared styles

#### Reviewers should focus on:
Is it useful for everyone? or only me?

#### Screenshot
blueprint-colors
bluebrint_sketchpalette

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/blueprint](https://github.com/palantir/blueprint), @estevesd! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by estevesd** [comment]
perhaps this should be added to the kit instead of a separate library ?

**Comment by aycai** [comment]
Yep, adding it to the kit makes sense - components and icons will benefit from this!

Sketch currently treats text and layer styles as separate lists, I think removing the text colors and adding them into their respective text styles makes more sense.

**Comment by aycai** [comment]
Checked the file in #2817, looks good there 👍

**Comment by aycai** [comment]
hey @estevesd, wanted to close the loop here. We're planning on merging in #4007 which I believe contains these changes, so going to close this PR. Does that sound good?

**Comment by estevesd** [comment]
Hi @aycai. Sounds very good. Awesome work from @terpimost on #4007

**Pull request closed without merging**
