### PR TITLE
add undefined and null to safeInvoke signature

### LINKED ISSUE #663: safeInvoke typings don't work with strict null checks
`safeInvoke` is a useful utility function, however it's unusable with `strictNullChecks` enabled.
Since it's defined without `undefined` in mind, using it results in the following error:

```
Argument of type '((a: A) => void) | undefined' is not assignable to parameter of type '(arg1: A) => void'.
  Type 'undefined' is not assignable to type '(arg1: A) => void'.
```

This makes it completely unusable, since it expects a non-undefined function to call (rendering the method obsolete).

### PR DESCRIPTION
**Pull request by JKillian**
#### Reviewers should focus on:

Does this solve usage in a `strictNullChecks` environment?

### CODE REVIEW

**Comment by giladgray** [comment]
i don't think this'll solve the non-zero arguments case: `safeInvoke(onClick, e)`

**Comment by invliD** [comment]
@giladgray You're correct, it only works for the no-arguments case.

**Comment by JKillian** [comment]
Whoops, sorry all. Just pushed a commit that should be better. Open question though, should we allow `undefined` only or `undefined | null`?

**Comment by invliD** [comment]
Works for me (for the `undefined` case).

**Comment by giladgray** [comment]
no need to include `null`. this looks great!

**Comment by JKillian** [comment]
Actually, on 2nd thought, I still don't know if I did this quite right. The issue is that if `func` is undefined, the return type should also be `undefined`. So it's possible that each return type should have an `| void` or `| undefined` tacked on to it...

**Pull request merged**
