### PR TITLE
[Table] Delete special styles for last cells in row

### LINKED ISSUE #628: Right edge of table extends 1px too much
image
image

The rightmost column is misaligned with the header. If the table is smaller than the body content, it creates a double border

### PR DESCRIPTION
**Pull request by cmslewis**
#### Changes proposed in this pull request:

Delete special styles for last cell in row and last cell in table. These styles were presumably present to hide borders appropriately when cells filled the table horizontally, but the styles didn't actually look perfect in that case. Removing them looks generally better all around.

#### Reviewers should focus on:

- Are you okay with the After style in each screenshot? (@themadcreator would love your thoughts especially)
- Am I missing any edge cases?

##### Chrome

_Before:_
before3
before2
before1

_After:_
after3
after2
after1

##### Firefox

_Before:_
image
image
image

_After:_
image
image
image

Note: This PR also partly addresses #516:
image

### CODE REVIEW

**Comment by giladgray** [comment]
only weirdness i can find: 
image

looks great otherwise!

**Comment by cmslewis** [comment]
@giladgray Maybe we can add a CSS class when the table cells start to horizontally overflow the table container. All my other ideas have failed me. Thoughts?

**Comment by cmslewis** [comment]
@llorca @gscshoyru regarding #516: I was referring to the fact that before, the blue border was 1px off on the right side; now, it aligns perfectly. Didn't attempt to address the left side (I guess I misunderstood the intent of that issue).

**Comment by cmslewis** [comment]
@llorca - regarding #516, here's what we do on the left border of a selection (blue border is outset) vs. on the bottom border of a selection (blue border is inset). Should we handle both cases in the same way? Won't fix all the `overflow: hidden` issues, but will at least reveal the left border of a selection.

image

**Comment by cmslewis** [comment]
@llorca - I'm slowly going insane. I reverted the commit in this PR to try a different direction, and all the misalignment issues in #628 have gone away, as have the double-border issues introduced by the original change in this PR. Might this issue have been addressed by other recent work?

**Pull request closed without merging**
