### PR TITLE
Prepare Release 1.20.0

### PR DESCRIPTION
**Pull request by cmslewis**
:fireworks: **Highlights**: `Table` batch cell rendering and other performance improvements

:book: **Latest docs**: [blueprintjs.com/docs](http://blueprintjs.com/docs)

## `@blueprintjs/core 1.20.0`
- __NEW__ Added four UI icons (#1221)
    - Bank account, IP address, cell tower, ID number
        screen shot 2017-06-13 at 8 57 11 am screen shot 2017-06-13 at 8 57 17 am  screen shot 2017-06-13 at 8 57 03 am screen shot 2017-06-13 at 8 57 23 am

## `@blueprintjs/datetime 1.17.0`
- __NEW__ `TimePicker` `disabled` prop (#1219) (🎩 @AlexMarvelo o)

## `@blueprintjs/table 1.17.0`
- 🌟 __NEW__ `Table` cells are now batch-rendered within each frame when scrolling (#1201)
    - This yields much smoother scrolling, with the tradeoff of showing momentary flashes of white as rendering catches up.
    - This batching behavior is not yet user toggle-able or configurable, but will be in the future.
        
- __NEW__ `ColumnHeaderCell`/`RowHeaderCell` `index` prop, which is passed to callbacks if provided (#1210)
    - No more having to instantiate new anonymous callback functions when rendering either of these components; the `index` can be passed directly to a persistent callback function instance.
- __NEW__ `ColumnHeaderCell`/`RowHeaderCell` `renderMenu` prop
    - `renderMenu` is an example of a callback that henceforth can be instantiated only once, because it receives the row/column `index` as a parameter.
    - `menu` is now deprecated in favor of `renderMenu` (#1218)
- __NEW__ `getShallowUnequalKeyValues` and `getDeepUnequalKeyValues` utility functions (#1222)
    - These functions streamline debugging of `shouldComponentUpdate` methods; they will thus be more useful for Blueprint _contributors_ than for Blueprint _consumers_. 
- __Fixed__ `Table` `componentWillReceiveProps` now responds to more prop changes and updates the component accordingly (#1165)
-  __Fixed__ `ColumnHeader`/`RowHeader` `shouldComponentUpdate` issues (#1215) (#1217)

### CODE REVIEW

**Comment by giladgray** [comment]
@cmslewis build failed cuz `site-docs` has some invalid versions in package.json. gotta audit those and make sure they all line up with latest in each other package.json

**Comment by giladgray** [comment]
- [ ] list the new icons
- [ ] prefer to put `ComponentName` as first word in note: "__NEW__ `TimePicker` `disabled` prop"
- [ ] add "(:tophat: @ AlexMarvelo)" to datetime note cuz it's external contrib
- [ ] we should add a GIF for the batching so folks know what to expect
- i don't put parens around issue numbers, but i kinda like it 🤷‍♂️

**Comment by adidahiya** [comment]
datetime 1.17, not 0.17

**Comment by cmslewis** [comment]
@giladgray the parens around issue/PR numbers come from my copy-pasting the commit descriptions directly into the PR description. I could take them or leave them.

**Comment by tgreenwatts** [comment]
"This batching behavior is not yet user toggle-able or configurable, but we want it to be in the future." -> "This batching behavior is not yet user toggle-able or configurable, but will be in the future."
pls danke

**Comment by cmslewis** [comment]
@tgreenwatts done

**Comment by waterscaleb** [comment]
I am using the blueprints/Table in a GoldenLayout container and having issues trying to render new cells on container events. Is there plans to have a hook for batch rendering?

**Comment by tgreenwatts** [comment]
Hi @waterscaleb - I moved your question into a separate ticket here https://github.com/palantir/blueprint/issues/1317. This PR is closed and not relevant

We've got a lot of vacations right now, so we'll probably respond next week. Thanks!

**Pull request merged**
