### PR TITLE
Fix fixed position on Collapse child / Improved documentation for localization of Datetime components 

### PR DESCRIPTION
**Pull request by Lumyo**
#### Checklist

- [ ] Includes tests
- [ ] Update documentation

#### Changes proposed in this pull request:

Improved the documentation for the localization of Datetime components.
The current example doesnt work, as it is using the default LocaleUtil implementation which just implements english language ( https://github.com/gpbl/react-day-picker/blob/v7.3.0/src/LocaleUtils.js )

I've added an example following the example in the documentation of react-day-picker to implement localization using moment  ( http://react-day-picker.js.org/docs/localization ), and added a link pointing towards this page, for people needing more detailed example on how to actually override the LocaleUtil functions on the default implementation.

#### Screenshot

Edit : [Added details for bug fix on Collapse ](https://github.com/palantir/blueprint/pull/3960#issuecomment-586400376)

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/blueprint](https://github.com/palantir/blueprint), @Lumyo! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by Lumyo** [comment]
I have added another fix to this pull request, concerning a bug when using fixed position on a child in a collapse node.
I wanted to do a separate pull request for this second thing, but looks like it got added here automatically (My bad, Im not yet very familiar with the proper way to do things on Github)

I've made an example here to reproduce the issue I fixed with this second commit :
https://codesandbox.io/s/blueprintjs-collapse-fixed-position-iiu13

When you expand the collapse, the Component with fixed position which should follow the cursor will have a wrong position (especially if you scroll down) when hovering the component inside the collapse. If you edit the css of the collapse to change the transform to "none" instead of "translateY(0)" it will work fine.

A more detailed explanation of this issue can be found here : https://achrafkassioui.com/blog/position-fixed-and-CSS-transforms/

**Comment by adidahiya** [comment]
In the future, please file an issue using the bug report template. I'm not sure about the bugfix for the Collapse component you've added here... did that kind of `position: fixed` code _ever work with Collapse? Did some use case stop working for you in a recent version of Blueprint?

**Comment by Lumyo** [comment]
Closing this, as i've splitted this into 2 pull requests 

#4003 
#4005

**Pull request closed without merging**
