### PR TITLE
Prepare release 1.25.2

### PR DESCRIPTION
**Pull request by cmslewis**
### 🐛  Bug fixes

- #1479 Fix `Table` sizing when shown in fluid-height container
- #1483 Fix `Table` SCSS compilation errors

### 🐛  Bug fixes

- #1478 Fix `normalize.css` version on docs site

### CODE REVIEW

**Comment by llorca** [comment]
We should include this too, it was also a regression: https://github.com/palantir/blueprint/pull/1478

**Comment by cmslewis** [comment]
@giladgray @adidahiya any idea why there are so many deletions in those icon files? not immediately evident to me why that happened when I ran the `prepRelease` script.

**Comment by adidahiya** [comment]
yes we should include the fix for the docs site.

**Comment by adidahiya** [comment]
would be great to include #1483 as well, since that's table related

**Comment by adidahiya** [comment]
you actually don't need to rebuild the docs site if you cherry-pick that commit ^

**Pull request merged**
