### PR TITLE
Emit ES modules in distribution

### LINKED ISSUE #309: Publish ES2015 modules in addition to CommonJS modules
Following up from a discussion here: https://github.com/palantir/blueprint/issues/245#issuecomment-263065706

> For consumers to utilize tree shaking, we'll have to publish ES6 modules in addition to CommonJS modules (static analysis tools work much better with the former). Shouldn't be too hard; we can use tsconfig.json inheritance and create multiple folders in dist/, dist/es6/ and dist/cjs/

### PR DESCRIPTION
**Pull request by adidahiya**
Fixes #309.

### Changes in this PR:

- Upgrade webpack-related dev dependencies
- Compile to ES modules
  - `tsc` has native support for this with `"modules": "es2015"`
  - We specifically __don't__ emit any other ES5-incompatible syntax, and since webpack 3 natively supports ESM, we don't require any additional tooling (like Babel)
- Telling consumers where to find these files
  - I basically copied what MobX does in its package manifests here and add a `"module"` field to package.json
  - Typings are still accessible at their old location. It is not an issue that the typings and ESM files are in different parts of the file tree; `tsc` and `webpack` resolve them independently

The output file tree looks like:

```
dist/
  package.json
  index.js      <--- common js
  common/
  ...
  esm/          <--- new hotness
    index.js
    common/
    ...
```

### Explicitly not done in this PR:

- Renaming `.js` files to `.mjs`
  - In Node.js, `.mjs` is preferred over `.js` if files with the same name exist
  - There's some history here https://github.com/nodejs/node-eps/pull/60 and in other threads across the internet; Node 8.5.0+ supports it natively. Also see http://2ality.com/2017/09/native-esm-node.html
  - Unfortunately, this doesn't work with webpack with my initial approach of placing `.js` files right next to their corresponding `.mjs` file -- when resolving a directory that contains both an `index.js` and `index.mjs` file, webpack prefers the `index.js`, which nullifies any tree shaking benefits. So if we can't put them in the same folder then I don't see any point in making this adhere to the Node standard (these are browser modules).

### Not addressed (requires follow up):

- Measure bundle execution time perf improvement in docs-app

### CODE REVIEW

**Comment by adidahiya** [comment]
It's strictly additive. I don't expect to make any breaks around this part of the distribution for 2.0.

**Comment by cmslewis** [comment]
@adidahiya Attempted to resolve merge conflits.

**Comment by adidahiya** [comment]
⚠️  do not merge this. I'm having issues with `.mjs` files in webpack and with my attempt to use the same folder tree for both CJS and ESM. I'm going to have to make some changes here.

**Comment by zerovox** [comment]
Do we need to do anything specific to consume this or will latest webpack just take care of all that?

**Comment by adidahiya** [comment]
Latest webpack just works out of the box.

**Pull request merged**
