### PR TITLE
Allow JSX elements as text

### PR DESCRIPTION
**Pull request by invliD**
#### Changes proposed in this pull request:

- Allow using `JSX.Element`s as text for `MenuItem`s, `Button`s, …

### CODE REVIEW

**Comment by giladgray** [comment]
@invliD why? _i need a reason_ 🎶 

- `Button` already supports JSX.Element as `children`: `<Button><jsx /></Button>`
- `MenuItem` explicitly doesn't support JSX.Element because it's too easy to abuse 
  - traditional menus should only contain string text, hence `icon` and `label` props. see any OS.
  - I'm open to changing this, but i need a reason 🎶 
- `IActionProps` is meant for simple text/icon-only buttons declared as JS objects (see `Toast.action`)

**Comment by giladgray** [comment]
@invliD also, mind trying something badass? follow these instructions, let's see if we can get you a preview comment: https://github.com/palantir/blueprint/pull/481#issuecomment-272837629

**Comment by invliD** [comment]
test

**Comment by invliD** [comment]
<h3>Test</h3>

Preview: <strong><a href='https://circleci.com/api/v1/project/invliD/blueprint/9/artifacts/0//home/ubuntu/blueprint/packages/docs/dist/index.html' target='_blank'>docs</a></strong>
Coverage: <a href='https://circleci.com/api/v1/project/invliD/blueprint/9/artifacts/0//home/ubuntu/blueprint/packages/core//coverage/PhantomJS%202.1.1%20%28Linux%200.0.0%29/index.html' target='_blank'>core</a> | <a href='https://circleci.com/api/v1/project/invliD/blueprint/9/artifacts/0//home/ubuntu/blueprintpackages/datetime//coverage/PhantomJS%202.1.1%20%28Linux%200.0.0%29/index.html' target='_blank'>datetime</a>

**Comment by giladgray** [comment]
🎆  🎆  🎆  🎆  🎆  🎆  🎆  🎆  🎆  

what is the secret to your wisdom?

**Comment by invliD** [comment]
@giladgray I fixed the publish script, I'm moving that to a separate PR.

**Comment by cmslewis** [comment]
@invliD - interesting thought here. I agree with @giladgray that it'd be great to see some motivating use cases before moving forward with this. Can you share screenshots of some stuff this change would help you accomplish? Otherwise I prefer minimizing API surface area.

**Comment by michael-yx-wu** [comment]
Since the `Menu` is used to replace the browser context menu, this means things like "open in a new tab" is no longer possible unless you implement. It's possible to do this today, but requires some bad hacks: get a ref to an icon and changing the `MenuItem`'s target on mouse over 😱 

Supporting JSX would let you add a button to fulfill the same functionality. That being said, instead of opening up the floodgates of arbitrary JSX, we could be more conservative and add a prop to `MenuItem` like `includeNewTabButton` that does this for you.

**Comment by invliD** [comment]
@michael-yx-wu That's not the original purpose of this PR, though. I'm trying to add an icon component to a menu item of which I do not know the css class (I only have a React component that represents the icon).

**Comment by adidahiya** [comment]
Briefly discussed offline with @giladgray; I think we should just go ahead and allow JSX. Can you resolve the merge conflicts @invliD?

**Comment by llorca** [comment]
Can you elaborate? We made a thoughtful decision a while ago regarding this, and we've enforced it for good reasons. Why change it now?

**Comment by giladgray** [comment]
context: @invliD has a custom `SVGIcon` component that he wants to use in menu items, but there's no way to provide a custom component as icon or text. his workaround has been to apply a CSS class to the `MenuItem` for the SVG icon.

After some more discussion with the team, we are _not prepared_ to accept this change. `MenuItem` is intended to be a simple text-only affair; if you need more complex content then you should simply apply the class name to your own elements, like the [`Navigator` (docs search)](https://github.com/palantir/blueprint/blob/master/packages/docs/src/components/navigator.tsx#L129).

Our counter-proposal is to change `iconName: string` to `icon: string | JSX.Element` in 2.0, particularly as we invest in our own `SVGIcon` component #365.

**Comment by adidahiya** [comment]
Just got linked to this thread again... I don't think we should wait until 2.0 to accept `icon: string | JSX.Element`, it's an additive change that could be useful immediately.

**Comment by giladgray** [comment]
@adidahiya sure, works for me!

**Pull request closed without merging**
