### PR TITLE
feat: new icons - array + variants

### PR DESCRIPTION
**Pull request by aycai**
#### Changes proposed in this pull request:

6 new icons:
- array
- bolean array
- date array
- numeric array
- string array
- timestamp array

#### Screenshot

Screen Shot 2020-09-30 at 1 00 42 AM

### CODE REVIEW

**Comment by adidahiya** [comment]
[preview build](https://35606-71939872-gh.circle-artifacts.com/0/packages/docs-app/dist/index.html#icons)

**Review by adidahiya — APPROVED** [review]

**Comment by nrathi** [comment]
@adidahiya what needs to be done for `Classes.iconClass(...)` to work for these new icons?

**Comment by adidahiya** [comment]
@nrathi nothing, `Classes.iconClass(iconName: string | undefined)` accepts a string, rather than an enum

**Comment by nrathi** [comment]
Ah, it's not working for me :/. It seems like "bp3-icon-numeric" inserts content `::before`, but "bp3-icon-array-numeric" doesn't.

**Comment by nrathi** [comment]
Oh nevermind, icon fonts were deprecated her https://blueprintjs.com/docs/#core/components/icon.css.

**Comment by adidahiya** [comment]
Ah sorry, yeah... the icon font is deprecated, you should use the React components. I'll go ahead and add `/** @deprecated */` for more clarity.

**Pull request merged**
