### PR TITLE
Don't endorse react-router as the standard

### PR DESCRIPTION
**Pull request by adidahiya**
... solution for React applications.

There are other options, and I don't recommend it for our internal projects.

#### Changes proposed in this pull request:

#509 brought this to my attention. This is a small wording change.

### CODE REVIEW

**Comment by llorca** [comment]
Is there one you highly recommend?

**Comment by giladgray** [comment]
🏆  _nice_

**Comment by adidahiya** [comment]
@llorca the routing library I recommend is an internal library we maintain that stores routing state in a Redux store and doesn't use components to represent routes (that's my main gripe with react-router). It will be open sourced soon! cc @greglo @zerovox

**Comment by llorca** [comment]
Sounds neat 💯

**Comment by benny-medflyt** [comment]
@adidahiya hi is your routing library open source yet?

**Comment by codemau5** [comment]
@adidahiya When will the palantir routing library be available? we can't wait to use it!
what do you recommend we use in the meantime?

**Comment by adidahiya** [comment]
There's been a lot of internal progress made in getting it ready for open source, expect an update within this month. In the meantime, react-router is fine to use.

**Comment by YoavHortman** [comment]
@adidahiya I'd love an update about the router (:

**Comment by jbach** [comment]
@adidahiya Any updates on your router? It’s been a while :)

**Comment by adidahiya** [comment]
No updates on the router library, I'd encourage you to explore the many options already available in the React ecosystem since my last comment.

**Comment by jbach** [comment]
True, but I have yet to come across a router library that doesn't need a `Link` wrapper of some sorts.

**Pull request merged**
