### PR TITLE
[datetime] Increase gap between month selection text and caret

### PR DESCRIPTION
**Pull request by reiv**
#### Changes proposed in this pull request:

~~This PR adds `font-family: inherit` rules to the `<select>` and `<input>` elements used in the components of this package. Previously, these were set to the browser defaults (`sans-serif`); now, they should use the correct font stack.~~ Split off into #2362.

In particular, this fixes an issue where the caret of the month selector was overlapping the text, like this:

datepicker-font

(That's because the `measureTextWidth` function was producing measurements that incorrectly assumed the body font stack.)

This PR also adds 5px of extra space between the text and caret -- it looked off with no gap at all.

By the way, I think that the `TimePicker` should perhaps be displayed in a monospace font (an additional visual cue that this input field accepts time values), but that might be too opinionated so I left it at `inherit` for now.

### CODE REVIEW

**Comment by reiv** [comment]
<h3>Actually use font-family: inherit</h3>

Preview: <strong><a href='https://369-120046743-gh.circle-artifacts.com/0/home/circleci/project/packages/docs-app/dist/index.html' target='_blank'>documentation</a> | <a href='https://369-120046743-gh.circle-artifacts.com/0/home/circleci/project/packages/landing-app/dist/index.html' target='_blank'>landing</a> | <a href='https://369-120046743-gh.circle-artifacts.com/0/home/circleci/project/packages/table-dev-app/dist/index.html' target='_blank'>table</a></strong>

**Comment by giladgray** [comment]
@reiv i think the right thing to do here is to upgrade to normalize.css v8.0 which includes _this exact fix_: https://github.com/necolas/normalize.css/blob/master/CHANGELOG.md#800-february-2-2018

> Form inputs inherit `font-family`.

**Comment by reiv** [comment]
@giladgray Neat! There's four other instances of `font-family: inherit` in the `core` package CSS that would become unnecessary as well. Can I change this PR to update normalize or are there any stoppers for 8.0?

**Comment by giladgray** [comment]
@reiv go for it!

**Comment by reiv** [comment]
<h3>Revert font-family CSS rule changes</h3>

Preview: <strong><a href='https://398-120046743-gh.circle-artifacts.com/0/home/circleci/project/packages/docs-app/dist/index.html' target='_blank'>documentation</a> | <a href='https://398-120046743-gh.circle-artifacts.com/0/home/circleci/project/packages/landing-app/dist/index.html' target='_blank'>landing</a> | <a href='https://398-120046743-gh.circle-artifacts.com/0/home/circleci/project/packages/table-dev-app/dist/index.html' target='_blank'>table</a></strong>

**Pull request merged**
