### PR TITLE
[popover2] feat(ContextMenu2): support popoverProps.rootBoundary

### LINKED ISSUE #5411: Initial location of `ContextMenu2` is misplaced when triggered inside a `Drawer`
#### Environment

- __Package version(s)__: `@blueprintjs/core@4.5.1`, `@blueprintjs/popover2@1.4.1`
- __Operating System__: macOS Monterey 12.4, arm64
- __Browser name and version__: Chrome 103.0.5060.53

#### Code Sandbox

Link to a minimal repro (fork [this code sandbox](https://codesandbox.io/s/blueprint-sandbox-et9xy)): 
https://codesandbox.io/s/blueprintjs-contextmenu2-in-drawer-wrong-position-w8jeu4

#### Steps to reproduce

1. Right click a ContextMenu2 trigger inside an opened drawer (in my setup the drawer was opened from right which is the default)
2. You should see that the ContextMenu is displayed at the top-most left-most position (I would guess 0, 0).

#### Actual behavior

The ContextMenu2 appears at the top-left corner.

#### Expected behavior

The ContextMenu2 should appear near where the trigger is.

#### Possible solution

- From https://github.com/palantir/blueprint/issues/4047 `johanwilson` suggests to use `boundary="viewport"` to mitigate the seemingly similar problem, however the popoverProps accepted by `ContextMenu2` explicitly doesn't includes this attribute (see https://blueprintjs.com/docs/#popover2-package/context-menu2). I've tried to just blindly ignore the TypeScript error and add such prop, but found no luck.

### PR DESCRIPTION
**Pull request by GalvinGao**
#### Checklist

- [ ] Includes tests
- [x] Update documentation

#### Changes proposed in this pull request:

- To enable overriding the default `rootBoundary` value in `ContextMenu2` component.

#### Reviewers should focus on:

- Default value done right? (or not?)

#### Screenshot

N/A: I'm unsure exactly how to test such change. I've tried to just add a Example component in the docs by following what other documents appear to do, but I found that the problem mentioned in #5411 is not reproducible within the docs-app for unknown reasons. Therefore I'm unsure if adding the `rootBoundary` props to the `ContextMenu2` will actually open the door for developers to mitigate this issue. Any help would be appreciated.

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/blueprint](https://github.com/palantir/blueprint), @GalvinGao! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by adidahiya** [comment]
@GalvinGao I edited your change to have a more minimal code diff.

I think we should test this change in the docs app or a unit test before merging. You could add a ContextMenu2 to the Drawer example in the docs-app for testing: https://github.com/palantir/blueprint/blob/develop/packages/docs-app/src/examples/core-examples/drawerExample.tsx

You may need to set `boundary` instead of `rootBoundary` to fix the problem. See the popper.js docs: https://popper.js.org/docs/v2/utils/detect-overflow/#boundary

**Comment by adidahiya** [comment]
@GalvinGao are you still interested in this PR? Can you add a unit test?

**Comment by GalvinGao** [comment]
> @GalvinGao are you still interested in this PR? Can you add a unit test?

Just got time. Gonna add it today or tomorrow.

**Comment by GalvinGao** [comment]
Added docs & unit tests. Ready for review ;)

**Review by adidahiya — APPROVED** [review]
looks good :shipit: 

image

**Pull request merged**
