### PR TITLE
[datetime] fix(DateInput): don't close when clicking time arrows

### LINKED ISSUE #3474: DateInput popover closes when clicking TimePicker arrow after changing month
#### Environment

- __Package version(s)__: @blueprintjs/datetime 3.19.0, @blueprintjs/datetime 3.14.0
- __Browser and OS versions__: FF, Chrome, IE11

#### Steps to reproduce

Make the following change to the DateInput example:
```diff
diff --git a/packages/docs-app/src/examples/datetime-examples/dateInputExample.tsx b/packages/docs-app/src/examples/datetime-examples/dateInputExample.tsx
index ada2350..ffc6ddb 100644
--- a/packages/docs-app/src/examples/datetime-examples/dateInputExample.tsx
+++ b/packages/docs-app/src/examples/datetime-examples/dateInputExample.tsx
@@ -59,6 +59,7 @@ export class DateInputExample extends React.PureComponent<IExampleProps, IDateIn
                     defaultValue={new Date()}
                     onChange={this.handleDateChange}
                     popoverProps={{ position: Position.BOTTOM }}
+                    timePickerProps={this.state.timePrecision ? {showArrowButtons: true} : undefined}
                 />
                 <MomentDate date={date} />
             </Example>
```
then:
1. set the **Date format** to _YYYY-MM-DD HH:mm:ss (moment)_
1. set the **Time precision** to e.g. _Minute_
1. click in the date input field
1. go to the previous (or next) month
1. click one of the time picker arrows (up or down)

#### Actual behavior

The DateInput popover is closed, time in the input field is unchanged.

#### Expected behavior

The DateInput popover stays open, time in the input field is updated.

#### Possible solution

The whole thing appears to balance on how `registerPopoverBlurHandler()` in `dateInput.tsx` works: when clicking next/previous month, this registers a blur handler. When clicking on a time picker arrow (an svg), `e.relatedTarget` inside `handlePopoverBlur(e)` is `null`/`undefined` and `document.activeElement` is `<body>` (that is, since `3.9.0` i.e. my own PR https://github.com/palantir/blueprint/pull/3471 — not that it is functionally any different for `3.8.0`). So the code assumes there was a click somewhere else and closes the popover.

I've looked into various approaches to tackle this, but haven't found anything that would fit. I'm willing to help make this work, let me know!

### PR DESCRIPTION
**Pull request by jez321**
#### Checklist

- [x] Includes tests
- [ ] Update documentation

#### Changes proposed in this pull request:

- Set tabIndex=-1 on the timepicker arrow span element to ensure e.relatedTarget on the FocusEvent passed to handlePopoverBlur in dateInput is valid, preventing inappropriate closing of the popover.

Added tests and checked in latest Chrome, Firefox and Safari.

#### Reviewers should focus on:

- Whether the referenced bug has been fixed
- Whether setting tabIndex=-1 has any other side effects

#### Screenshot

Before | After
---- | ----
dpbefore | dpfixed

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/blueprint](https://github.com/palantir/blueprint), @jez321! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by jez321** [comment]
After doing a bit more thinking I think it might be better to find a way to fix this that doesn't require as a big a change as changing the timepicker arrows from a span to button so I'll play around a bit more and see if I can come up with something.

**Comment by jez321** [comment]
I've reverted the element type change and simply set tabIndex=-1 on the timepicker arrow span to ensure a valid relatedTarget is passed to focus events (specifically the FocusEvent passed to handlePopoverBlur in dateInput) which appears to fix the issue. Please let me know if this is acceptable or if you would like any changes to be made.

**Review by adidahiya — APPROVED** [review]
great, thanks!

**Comment by adidahiya** [comment]
[PR preview docs build](https://33901-71939872-gh.circle-artifacts.com/0/packages/docs-app/dist/index.html#datetime/dateinput)

it's a little hard to test in the docs site. we should probably add this option to show time picker arrows on all the date input components, similar to DatePicker:

image

**Comment by IzaGz** [comment]
I still have the problem on latest versions! ((( please help!

**Pull request merged**
