### PR TITLE
add .eslintignore like .stylelintignore

### PR DESCRIPTION
**Pull request by giladgray**
#### Changes proposed in this pull request:

- no need to lint compiled or external JS files as they'll never pass our muster
- alphabetize entries in both linter ignore files.

### CODE REVIEW

**Comment by adidahiya** [comment]
TSLint now lints JS files. Let's try that instead https://palantir.github.io/tslint/2016/11/17/new-for-4.0.html

**Comment by giladgray** [comment]
ok sweet i'm trying out TSLint for JS. current blocker: TS supports trailing commas in function calls, JS does not. is it possible to disable a rule only for JS files?

```js
gulp.task("compile", (done) => rs(
    "sass-variables",
    ["sass-compile", "typescript-compile", "copy-files"],
    done[,] // <-- offender
));
```

**Comment by giladgray** [comment]
💥  `jsRules`

**Comment by giladgray** [comment]
wait not so simple... we want trailing commas in JS _objects_ but not in JS _functions_... that may not be possible. @JKillian any insight?

**Comment by adidahiya** [comment]
@giladgray doesn't look like that's an option [here](https://palantir.github.io/tslint/rules/trailing-comma/). We should file a FR to make this work for JS files since it's invalid syntax (either check if the file is `.js` and don't treat it as a lint failure, or allow opting out of trailing commas in function param lists with a new option).

PS. refer to @nchen63 for TSLint requests these days

**Comment by JKillian** [comment]
The good news is that trailing commas for function params and arguments are something that will be allowed in upcoming versions of js: https://github.com/tc39/proposals/blob/master/finished-proposals.md

The bad news is that no current versions of Node support this: http://node.green/#trailing-commas-in-function-syntax

Don't know of any good workaround right now for TSLint unfortuantely

**Pull request closed without merging**
