### PR TITLE
[Core] Fixed not applying intent color for icon inside menu component

### LINKED ISSUE #3593: Icons inside Menu component does not have intent applied
#### Environment

- __Package version(s)__: 3.15.1
- __Browser and OS versions__: probably all

#### Actual behavior
Similar to #3042, but affecting `Menu` component, `Icon`s passed to `MenuItem` components does not have intent color applied

#### Expected behavior
Intent colors should be applied

#### Possible solution
Similar ro #3355 , I'll do PR soon.

Does anyone have other components in mind, that may have a similar issue?

### PR DESCRIPTION
**Pull request by jacekjagiello**
#### Fixes #3593 

- [x] Includes tests
- [x] Update documentation

#### Changes proposed in this pull request:

Fixed not applying intent color for icons inside menu component

Screenshot_2019-06-13 Blueprint – Documentation copy
Screenshot_2019-06-13 Blueprint – Documentation

### CODE REVIEW

**Comment by adidahiya** [comment]
@pkwi what do you think, should we support intents here?

**Comment by adidahiya** [comment]
@adamstorr same question as above ^

**Comment by brent824** [comment]
Uh huh

**Comment by adidahiya** [comment]
I'm not convinced that this actually makes sense in our design system, and I think https://github.com/palantir/blueprint/pull/3598 might have been a design mistake as well. Closing this until we have some more input from Palantir designers...

**Pull request closed without merging**
