### PR TITLE
Prepare release v1.28.0

### PR DESCRIPTION
**Pull request by llorca**
:book: **Latest docs**: [blueprintjs.com/docs](http://blueprintjs.com/docs)

### 💎  New features
- #1518 #1570 Added __nine__ new icons
  - `pt-icon-filter-keep`, `pt-icon-filter-remove`, `pt-icon-key`, `pt-feed-subscribed`, `pt-icon-widget-button`, `pt-icon-widget-header`, `pt-icon-widget-footer`, `pt-icon-header-one`, `pt-icon-header-two`

### 💎  New features

- #1550 `TruncatedFormat` now receives parent `width`/`height` as props
    - The props slightly improve performance by helping `TruncatedFormat` avoid re-measuring if the parent size didn't change across updates

### 🐛  Bug fixes

- #1515 Fix column header borders on ghost cells
- #1523 Select the target cell on right-click
- #1524 Improve shift-select behavior
- #1541 Move focused cell when columns/rows are reordered

### 💎  New features

- #1493 `Select`/`MultiSelect`/`Omnibox` `initialContent` prop is rendered when query is empty (instead of full `items` list)
  - This is distinct from `noResults`, which is rendered when a non-empty query returns zero results
- #1537 `Select` `disabled` prop disables the `Popover`
  - You must manually disable your target element

## Documentation

- #1528 Correct icon font variable names
- #1542 Add copy/paste to sortable table example
- #1522 Improve the `Table` development preview page
- #1551 Split __labs__ documentation page into one page per component (like other packages)
  - ⚠️ This change breaks URLs; you'll need to update any bookmarks manually

### CODE REVIEW

**Comment by llorca** [comment]
Looks like we've got another flaky test :(

**Comment by giladgray** [comment]
@llorca flaky test? things look good to me.

edited release notes to provide context on new labs props, moved some more things to Documentation section.

need more context on Table new feature: what issue does this fix? can we describe it differently to capture the __WHY__?

**Comment by cmslewis** [comment]
@giladgray done

**Comment by llorca** [comment]
@giladgray yeah I had to manually retrigger the build. Focus stuff again https://circleci.com/gh/palantir/blueprint/3945

**Comment by tgreenwatts** [comment]
Um given that https://github.com/palantir/blueprint/pull/1515 seems to be broken again, should we remove it from the notes?

**Comment by tgreenwatts** [comment]
Actually I take it back. It appears to work on this PR. It didn't on other recent table ones, but maybe they were just based on older code?

**Pull request merged**
