### PR TITLE
Move bourbon from devDependencies to dependencies

### PR DESCRIPTION
**Pull request by cyu06**
#### PR checklist

- [X] Addresses an existing issue: #123
- [X] New feature, bugfix, or enhancement
  - [ ] Includes tests
- [ ] Documentation update

#### What changes did you make?

Updates package.json to depend on bourbon

#### Is there anything you'd like reviewers to focus on?

### CODE REVIEW

**Comment by adidahiya** [comment]
Can we consider the tradeoffs here more closely? I'm not yet convinced this is the right direction; will the majority of our users be importing the `.scss` files?

**Comment by giladgray** [comment]
i'm not convinced either. it might be sufficient to add a note about Sass usage where we can tell users to install bourbon (or install blueprint + devDeps). would make sense alongside the Typescript usage section where they have to install typings.

**Comment by cyu06** [comment]
Alright, closing this to update docs

**Comment by dmackerman** [comment]
I'm not sure why the styling portion of the library should be treated any differently than the TS source? Would you only include the compiled `.js` files?

I'm not sure what your longer term goals for this framework are, but having a framework that's styled and built with SASS / LESS, but then not enabling the happy path of allowing end users to import and override SCSS variables to customize the look & feel seems strange. That's the beauty of SCSS anyway, isn't it? 

Just my 2 cents. 😄

**Comment by giladgray** [comment]
@dmackerman this is actually the first time we've distributed the Sass code along with the compiled CSS. we never had a reason to investigate consuming the Sass APIs outside the comforts of the monorepo. i can confirm it's on the roadmap though we haven't started planning. proposals welcome!

**Pull request closed without merging**
