### PR TITLE
[Core/Button] Fix minimal, active, disabled css style

### LINKED ISSUE #1701: [Button] Wrong onHover style on active, disabled and minimal button
### Bug report

- __Package version(s)__: 1.31.0

#### Steps to reproduce
Button and AnchorButton with "pt-minimal" style and active and disabled props `<Button className="pt-minimal" text="Button" disabled active/>` don't have the style that I would expect when on hover. This is how the button looks without having the pointer over it:
bug_1
And this is how it looks when the mouse is over it:
bug_2
With that style the button doesn't look active, it has the same style as a minimal and disabled button but not active.

### PR DESCRIPTION
**Pull request by franciscofabian**
#### Checklist

- [x] [Enable CircleCI for your fork](https://circleci.com/add-projects)

#### Changes proposed in this pull request:

Add missing styling for minimal, active, disabled buttons

#### Reviewers should focus on:

I think that I have added all the missed styles but maybe I forgot about something.

### CODE REVIEW

**Comment by franciscofabian** [comment]
<h3>fix dark color</h3>

Preview: <strong><a href='https://circleci.com/api/v1/project/franciscofabian/blueprint/51/artifacts/0//home/ubuntu/blueprint/packages/site-docs/dist/index.html' target='_blank'>documentation</a></strong>
Coverage: <a href='https://circleci.com/api/v1/project/franciscofabian/blueprint/51/artifacts/0//home/ubuntu/blueprint/packages/core//coverage/PhantomJS%202.1.1%20%28Linux%200.0.0%29/index.html' target='_blank'>core</a> | <a href='https://circleci.com/api/v1/project/franciscofabian/blueprint/51/artifacts/0//home/ubuntu/blueprintpackages/datetime//coverage/PhantomJS%202.1.1%20%28Linux%200.0.0%29/index.html' target='_blank'>datetime</a>

**Comment by llorca** [comment]
@franciscofabian thank you! Looks like you modified an automatically generated file. You should be modifying [the source file instead](https://github.com/palantir/blueprint/blob/master/packages/core/src/components/button/_common.scss)

**Comment by franciscofabian** [comment]
<h3>Merge pull request #5 from palantir/master</h3>

Preview: <strong><a href='https://circleci.com/api/v1/project/franciscofabian/blueprint/52/artifacts/0//home/ubuntu/blueprint/packages/site-docs/dist/index.html' target='_blank'>documentation</a></strong>
Coverage: <a href='https://circleci.com/api/v1/project/franciscofabian/blueprint/52/artifacts/0//home/ubuntu/blueprint/packages/core//coverage/PhantomJS%202.1.1%20%28Linux%200.0.0%29/index.html' target='_blank'>core</a> | <a href='https://circleci.com/api/v1/project/franciscofabian/blueprint/52/artifacts/0//home/ubuntu/blueprintpackages/datetime//coverage/PhantomJS%202.1.1%20%28Linux%200.0.0%29/index.html' target='_blank'>datetime</a>

**Comment by giladgray** [comment]
@franciscofabian as others have said, this PR needs to be re-written to modify source code instead of compiled artifacts. will you be able to do that work soon?

**Comment by franciscofabian** [comment]
@giladgray yes, I will do it this week. I have been quite busy and I couldn't do it yet.

**Comment by giladgray** [comment]
@franciscofabian terrific! I'm going to close this PR in the meantime. Feel free to reopen this one or start a new one when you're ready 👍

**Pull request closed without merging**
