### PR TITLE
a11y(DatePicker): move year and month selects from caption to navbar (fixes tab order and a11y failure)

### LINKED ISSUE #6058: incorrect tab order in DatePicker header, DatePicker also failing aXe a11y checks
#### Environment

- __Package version(s)__: Latest
- __Operating System__: Windows
- __Browser name and version__: Chrome

#### Steps to reproduce

1. Run aXe devtools on any DatePicker
2. See failure:
image

Failure: a grid caption should not contain interactive elements. The caption is within the role="grid" element, and the grid's caption should not contain the selects, because it's supposed to be only that, a caption for the grid.

3. Tab through DatePicker. Element order goes left arrow -> right arrow -> month select -> year select. Should go from left to right visibily, left arrow ->  month select -> year select ->

#### Expected behavior

- Have correct tab order based on visual order of elements
- Don't fail aXe rules

#### Possible solution

Move month year selects to `DayPicker`'s `navbarElement` and out of its `captionElement`. Place in between the prev/next arrows. Modify CSS to keep visually same.

### PR DESCRIPTION
**Pull request by bvandrc**
Fixes #6058

Reason:
- Fix tab order of datepicker navbar
- Fix A11y failure issue-- grid caption should not contain interactive elements

#### Checklist

- [X] Includes tests
- [N/A] Update documentation

#### Changes proposed in this pull request:

Move Year and Month selects out of React-Day-Picker caption (`renderCaption`) to navbar (`renderNavbar`). Fixes tab order of these elements with the navigation arrows, and fixes accessibility issue-- a `grid` caption should not contain interactive elements. The caption is within the role="grid" element, and the grid's `caption` should not contain the `select`s, because it's supposed to be only that, a caption for the grid. 

A11y failures aside, these components generally make more sense as a "navigation" component than a "caption".

#### Screenshot
**Tab Order Before and After:**
ScreenRecorderProject1     ScreenRecorderProject2

**Proof that is visually and functionally same as before:**
ScreenRecorderProject3_2

**aXe failure:**

image

### CODE REVIEW

**Comment by adidahiya** [comment]
> grid caption should not contain interactive elements

@bvandercar-vt do you have documentation you can reference for this claim?

**Comment by bvandercar-vt** [comment]
> > grid caption should not contain interactive elements
> 
> @bvandercar-vt do you have documentation you can reference for this claim?

aXe failure:

image

Problem is that the `caption` is within the `role="grid"` element. Not only does this break the above a11y rule, it probably shouldn't be part of the calendar days grid anyways.

Plus, this fixes the tab order.

**Comment by bvandercar-vt** [comment]
@adidahiya made a new update. Realized that before, the Month Year text was in the `grid` caption which could be beneficial to screenreaders. So, added a `screenreader-only` invisible caption that includes that text in the caption. That element is now the new `datePickerCaption`.

**Comment by bvandrc** [comment]
> > grid caption should not contain interactive elements
> 
> @bvandercar-vt do you have documentation you can reference for this claim?

Updated the PR description with the aXe failure and more detailed info.

**Comment by bvandrc** [comment]
@adidahiya I added GIFs to PR description

**Comment by bvandrc** [comment]
@adidahiya refactored this

**Comment by adidahiya** [comment]
thanks for your effort so far on this PR @bvandercar-vt. I feel like this change has the chance to be breaking in some very rare cases since we try to guarantee no DOM layout breaks in Blueprint components. There are also some major changes to date picker caption / navbar rendering coming in react-day-picker v8 (see https://github.com/palantir/blueprint/pull/5935). For these reasons, I feel like it's probably best to wait to make this change until we upgrade to react-day-picker v8, where we expect to make some DOM breaking changes anyway. This should be possible in the next few weeks / month.

**Comment by adidahiya** [comment]
@bvandercar-vt we are now using react-day-picker v8 in the "V3" components in `@blueprintjs/datetime2`. All a11y fixes should be made there.

Most of the code paths now use react-day-picker's caption rendering, so if there are a11y issues there, you should bring it up with that library maintainer.

One code path goes through a custom caption renderer that lives inside Blueprint code, though: non-contiguous date range pickers with multiple months. Those [utilize](https://github.com/palantir/blueprint/blob/94a1963648bc5d820a66c8e64ee8eeae22327369/packages/datetime2/src/components/date-range-picker3/nonContiguousDayRangePicker.tsx#L81) a custom [`<DatePicker3Caption>` component](https://github.com/palantir/blueprint/blob/94a1963648bc5d820a66c8e64ee8eeae22327369/packages/datetime2/src/components/react-day-picker/datePicker3Caption.tsx).

I'm going to close this PR for now, and if you want to pick up the a11y work, you may do so in a new PR. Thanks!

**Pull request closed without merging**
