### PR TITLE
Fix <Dialog /> position in IE

### PR DESCRIPTION
**Pull request by thepocp**
#### Checklist

- [ ] Includes tests
- [ ] Update documentation

#### Changes proposed in this pull request:
I set the `.bp3-dialog-container` height 

#### Reviewers should focus on:
Dialog component

#### Screenshot

Screenshot 2019-11-29 at 17 03 40
Screenshot 2019-11-29 at 17 03 49

### CODE REVIEW

**Comment by themadcreator** [comment]
This needs to merge in latest develop to fix the build

**Comment by thepocp** [comment]
@themadcreator I merged the develop branch, but the build still failed

**Comment by adidahiya** [comment]
[latest docs preview here](https://29044-71939872-gh.circle-artifacts.com/0/home/circleci/project/packages/docs-app/dist/index.html#core/components/dialog)

unfortunately this causes an issue in Chrome and Firefox where you can't scroll to the top of tall overflowing dialogs:

**Comment by adidahiya** [comment]
@thepocp sorry for the delayed review, but it's been a while since the last comment and I'm going to close this PR for now. Leave a comment if you'd like me to re-open.

**Pull request closed without merging**
