### PR TITLE
fix bourbon deprecations warnings

### LINKED ISSUE #674: Bourbon deprecations
Hi,

just FYI.

since I use the scss directly, and use latest `Bourbon`, I see this warning. Hope you will address before next major release of `Bourbon`

```
WARNING: [Bourbon] [Deprecation] `background` is deprecated and will be removed in 5.0.0. We suggest using an automated prefixing tool, like Autoprefixer.
Backtrace:
	node_modules/bourbon/app/assets/stylesheets/_bourbon-deprecate.scss:10, in mixin `-bourbon-deprecate`
	node_modules/bourbon/app/assets/stylesheets/_bourbon-deprecate.scss:17, in mixin `-bourbon-deprecate-for-prefixing`
	node_modules/bourbon/app/assets/stylesheets/css3/_background.scss:7, in mixin `background`
	node_modules/@blueprintjs/core/src/common/_mixins.scss:38, in mixin `linear-gradient-with-fallback`
	node_modules/@blueprintjs/core/src/components/button/_common.scss:114, in mixin `pt-button`
	node_modules/@blueprintjs/core/src/components/forms/_common.scss:201

WARNING: [Bourbon] [Deprecation] `_linear-gradient-parser` is deprecated and will be removed in 5.0.0.
Backtrace:
	node_modules/bourbon/app/assets/stylesheets/helpers/_linear-gradient-parser.scss:3, in function `_linear-gradient-parser`
	node_modules/bourbon/app/assets/stylesheets/css3/_background.scss:29, in mixin `background`
	node_modules/@blueprintjs/core/src/common/_mixins.scss:38, in mixin `linear-gradient-with-fallback`
	node_modules/@blueprintjs/core/src/components/button/_common.scss:114, in mixin `pt-button`
	node_modules/@blueprintjs/core/src/components/forms/_common.scss:201

WARNING: [Bourbon] [Deprecation] `background` is deprecated and will be removed in 5.0.0. We suggest using an automated prefixing tool, like Autoprefixer.
Backtrace:
	node_modules/bourbon/app/assets/stylesheets/_bourbon-deprecate.scss:10, in mixin `-bourbon-deprecate`
	node_modules/bourbon/app/assets/stylesheets/_bourbon-deprecate.scss:17, in mixin `-bourbon-deprecate-for-prefixing`
	node_modules/bourbon/app/assets/stylesheets/css3/_background.scss:7, in mixin `background`
	node_modules/@blueprintjs/core/src/common/_mixins.scss:38, in mixin `linear-gradient-with-fallback`
	node_modules/@blueprintjs/core/src/components/button/_common.scss:139, in mixin `pt-button-hover`
	node_modules/@blueprintjs/core/src/components/button/_common.scss:120, in mixin `pt-button`
	node_modules/@blueprintjs/core/src/components/forms/_common.scss:201

WARNING: [Bourbon] [Deprecation] `_linear-gradient-parser` is deprecated and will be removed in 5.0.0.
Backtrace:
	node_modules/bourbon/app/assets/stylesheets/helpers/_linear-gradient-parser.scss:3, in function `_linear-gradient-parser`
	node_modules/bourbon/app/assets/stylesheets/css3/_background.scss:29, in mixin `background`
	node_modules/@blueprintjs/core/src/common/_mixins.scss:38, in mixin `linear-gradient-with-fallback`
	node_modules/@blueprintjs/core/src/components/button/_common.scss:139, in mixin `pt-button-hover`
	node_modules/@blueprintjs/core/src/components/button/_common.scss:120, in mixin `pt-button`
	node_modules/@blueprintjs/core/src/components/forms/_common.scss:201

WARNING: [Bourbon] [Deprecation] `background` is deprecated and will be removed in 5.0.0. We suggest using an automated prefixing tool, like Autoprefixer.
Backtrace:
	node_modules/bourbon/app/assets/stylesheets/_bourbon-deprecate.scss:10, in mixin `-bourbon-deprecate`
	node_modules/bourbon/app/assets/stylesheets/_bourbon-deprecate.scss:17, in mixin `-bourbon-deprecate-for-prefixing`
	node_modules/bourbon/app/assets/stylesheets/css3/_background.scss:7, in mixin `background`
	node_modules/@blueprintjs/core/src/common/_mixins.scss:38, in mixin `linear-gradient-with-fallback`
	node_modules/@blueprintjs/core/src/components/button/_common.scss:200, in mixin `pt-dark-button`
	node_modules/@blueprintjs/core/src/components/forms/_common.scss:220

WARNING: [Bourbon] [Deprecation] `_linear-gradient-parser` is deprecated and will be removed in 5.0.0.
Backtrace:
	node_modules/bourbon/app/assets/stylesheets/helpers/_linear-gradient-parser.scss:3, in function `_linear-gradient-parser`
	node_modules/bourbon/app/assets/stylesheets/css3/_background.scss:29, in mixin `background`
	node_modules/@blueprintjs/core/src/common/_mixins.scss:38, in mixin `linear-gradient-with-fallback`
	node_modules/@blueprintjs/core/src/components/button/_common.scss:200, in mixin `pt-dark-button`
	node_modules/@blueprintjs/core/src/components/forms/_common.scss:220

WARNING: [Bourbon] [Deprecation] `background` is deprecated and will be removed in 5.0.0. We suggest using an automated prefixing tool, like Autoprefixer.
Backtrace:
	node_modules/bourbon/app/assets/stylesheets/_bourbon-deprecate.scss:10, in mixin `-bourbon-deprecate`
	node_modules/bourbon/app/assets/stylesheets/_bourbon-deprecate.scss:17, in mixin `-bourbon-deprecate-for-prefixing`
	node_modules/bourbon/app/assets/stylesheets/css3/_background.scss:7, in mixin `background`
	node_modules/@blueprintjs/core/src/common/_mixins.scss:38, in mixin `linear-gradient-with-fallback`
	node_modules/@blueprintjs/core/src/components/button/_common.scss:236, in mixin `pt-dark-button-hover`
	node_modules/@blueprintjs/core/src/components/button/_common.scss:215, in mixin `pt-dark-button`
	node_modules/@blueprintjs/core/src/components/forms/_common.scss:220

WARNING: [Bourbon] [Deprecation] `_linear-gradient-parser` is deprecated and will be removed in 5.0.0.
Backtrace:
	node_modules/bourbon/app/assets/stylesheets/helpers/_linear-gradient-parser.scss:3, in function `_linear-gradient-parser`
	node_modules/bourbon/app/assets/stylesheets/css3/_background.scss:29, in mixin `background`
	node_modules/@blueprintjs/core/src/common/_mixins.scss:38, in mixin `linear-gradient-with-fallback`
	node_modules/@blueprintjs/core/src/components/button/_common.scss:236, in mixin `pt-dark-button-hover`
	node_modules/@blueprintjs/core/src/components/button/_common.scss:215, in mixin `pt-dark-button`
	node_modules/@blueprintjs/core/src/components/forms/_common.scss:220

WARNING: [Bourbon] [Deprecation] `strip-units` is deprecated and will be removed in 5.0.0. Use the renamed `strip-unit` function instead.
Backtrace:
	node_modules/bourbon/app/assets/stylesheets/functions/_strip-units.scss:17, in function `strip-units`
	node_modules/@blueprintjs/core/src/common/_icons.scss:50, in mixin `pt-icon`
	node_modules/@blueprintjs/core/src/components/forms/_common.scss:231

WARNING: [Bourbon] [Deprecation] `placeholder` is deprecated and will be removed in 5.0.0. We suggest using an automated prefixing tool, like Autoprefixer.
Backtrace:
	node_modules/bourbon/app/assets/stylesheets/_bourbon-deprecate.scss:10, in mixin `-bourbon-deprecate`
	node_modules/bourbon/app/assets/stylesheets/_bourbon-deprecate.scss:17, in mixin `-bourbon-deprecate-for-prefixing`
	node_modules/bourbon/app/assets/stylesheets/css3/_placeholder.scss:2, in mixin `placeholder`
	node_modules/@blueprintjs/core/src/components/forms/_common.scss:99, in mixin `pt-input`
	app/..../blueprintjs/react-select/_control.scss:121

WARNING: [Bourbon] [Deprecation] `placeholder` is deprecated and will be removed in 5.0.0. We suggest using an automated prefixing tool, like Autoprefixer.
Backtrace:
	node_modules/bourbon/app/assets/stylesheets/_bourbon-deprecate.scss:10, in mixin `-bourbon-deprecate`
	node_modules/bourbon/app/assets/stylesheets/_bourbon-deprecate.scss:17, in mixin `-bourbon-deprecate-for-prefixing`
	node_modules/bourbon/app/assets/stylesheets/css3/_placeholder.scss:2, in mixin `placeholder`
	node_modules/@blueprintjs/core/src/components/forms/_common.scss:148, in mixin `pt-dark-input`
	app/..../blueprintjs/react-select/_control.scss:127

WARNING: [Bourbon] [Deprecation] `strip-units` is deprecated and will be removed in 5.0.0. Use the renamed `strip-unit` function instead.
Backtrace:
	node_modules/bourbon/app/assets/stylesheets/functions/_strip-units.scss:17, in function `strip-units`
	node_modules/@blueprintjs/core/src/common/_icons.scss:50, in mixin `pt-icon`
	app/..../blueprintjs/react-select/_control.scss:238

WARNING: [Bourbon] [Deprecation] `animation` is deprecated and will be removed in 5.0.0. We suggest using an automated prefixing tool, like Autoprefixer.
Backtrace:
	node_modules/bourbon/app/assets/stylesheets/_bourbon-deprecate.scss:10, in mixin `-bourbon-deprecate`
	node_modules/bourbon/app/assets/stylesheets/_bourbon-deprecate.scss:17, in mixin `-bourbon-deprecate-for-prefixing`
	node_modules/bourbon/app/assets/stylesheets/css3/_animation.scss:5, in mixin `animation`
	app/..../blueprintjs/react-select/_control.scss:260

WARNING: [Bourbon] [Deprecation] `strip-units` is deprecated and will be removed in 5.0.0. Use the renamed `strip-unit` function instead.
Backtrace:
	node_modules/bourbon/app/assets/stylesheets/functions/_strip-units.scss:17, in function `strip-units`
	node_modules/@blueprintjs/core/src/common/_icons.scss:50, in mixin `pt-icon`
	node_modules/@blueprintjs/core/src/components/tag/_common.scss:93, in mixin `tag-remove`
	app/..../blueprintjs/react-select/_multi.scss:42

WARNING: [Bourbon] [Deprecation] `strip-units` is deprecated and will be removed in 5.0.0. Use the renamed `strip-unit` function instead.
Backtrace:
	node_modules/bourbon/app/assets/stylesheets/functions/_strip-units.scss:17, in function `strip-units`
	node_modules/@blueprintjs/core/src/common/_icons.scss:23, in mixin `pt-icon-sized`
	node_modules/@blueprintjs/core/src/components/tag/_common.scss:125, in mixin `tag-remove-large`
	app/..../blueprintjs/react-select/_multi.scss:67
```

### PR DESCRIPTION
**Pull request by giladgray**
#### Changes proposed in this pull request:

- bump bourbon to latest 4.x
- stop using bourbon prefixer mixins. Bourbon has deprecated _all_ of them in favor of a tool like Autoprefixer. we already use Autoprefixer so this was easy.
- manually disable logging of bourbon deprecations warnings via handy Sass variable!
  - the only remaining warning is about `strip-units` being renamed, but nothing we can do as we're not on 5.0 yet.

cc @bsr203

### CODE REVIEW

**Comment by giladgray** [comment]
just `font-face()` and `position()`.

**Comment by adidahiya** [comment]
sweet, can we inline those in a follow-up PR? doesn't seem worth it for just two mixins.

**Comment by adidahiya** [comment]
I would even just get rid of any fancy `position()` usage and use plain scss

**Comment by omeid** [comment]
Is there an issue that tracks the possibility of removing bourbon?

Bourbon adds a fair bit to the amount of scss that needs to be parsed and processed (makes a difference with hot reloading for example) but doesn't seem to be providing much value.

**Comment by adidahiya** [comment]
@omeid yes, tracking that here https://github.com/palantir/blueprint/issues/875

**Pull request merged**
