### PR TITLE
.pt-intent-* by itself sets text color

### LINKED ISSUE #1019: Icon intents
I often see these colorized with custom CSS, would be nice to support this feature with `.pt-intent` classes.

### PR DESCRIPTION
**Pull request by giladgray**
#### Changes proposed in this pull request:

- this allows coloring icons, and any other arbitrary text!
- i audited all the examples and found only one actual issue (callouts).

#### Reviewers should focus on:

Go try adding `pt-intent-primary` to random elements! It works really nicely on icons, cards, table headers, etc.

The following components have minor visual changes as a result of this change. Are you ok with this or must we go in and cancel these color changes?

- input group icons are now colored according to group intent:
input-group-intent
(this makes me wonder if we should drop the [nasty] selector that cancels colors on input group icons when unfocused)

- form group label text is now colored according to group intent:
form-group-intent

### CODE REVIEW

**Comment by llorca** [comment]
Oof I can see the side effects coming with such a general rule. Let's do it incrementally and scope it to icons only for this one, and stick to your original solution from #1019: `.pt-icon-standard.pt-intent-* -> color: $pt-intent-*` (probably more like `[class*="pt-icon-"]` for the icon selector?)

**Comment by giladgray** [comment]
closing to refactor to target only icons

**Comment by adidahiya** [comment]
I understand the hesitation to implement a broad change here, but it's pretty easy to test the impact of this in large applications that already use a recent version of blueprint

**Comment by giladgray** [comment]
what did it for me is the image of labels above, with the two red text colors. we have `$pt-intent-colors` and `$pt-intent-text-colors` and i do not want to deal with ensuring that they're used correctly in every arbitrary component. easy enough to support icons right now though.

**Pull request closed without merging**
