### PR TITLE
Fix z-index stack for .pt-button-group and .pt-control-group elements

### PR DESCRIPTION
**Pull request by cmslewis**
(Sweeping up a couple final issues from #537, specifically from [these changes](https://github.com/palantir/blueprint/pull/537/files#diff-9f4ffc04872ae8416007b7851351b176) to `_control-group.scss`.)

### Before

(Note: I discovered these issues while working on the `NumericInput` component in #189.)

- If a control group has multiple consecutive buttons with an intent styling, the focus outlines will be improperly layered behind neighboring buttons. See here:

screen shot 2017-01-26 at 6 52 35 pm

- For buttons in a `.pt-control-group > .pt-button-group` with _no_ intent, a hovered neighbor would appear above a focused neighbor's outline:

image

Here's a GIF of the issues in action:

_Case 1: The buttons are **not** nested in a `.pt-button-group`:_

_Case 2: The buttons **are** nested in a `.pt-button-group`:_

 
## After:
After some z-index massaging, everything behaves as expected:

_Case 1: The buttons are **not** nested in a `.pt-button-group`:_

_Case 2: The buttons **are** nested in a `.pt-button-group`:_

### Dark Theme

Looks good as well.

_Case 1: The buttons are **not** nested in a `.pt-button-group`:_

_Case 2: The buttons **are** nested in a `.pt-button-group`:_

#### Reviewers should focus on:

- Does this handle all the cases?
- Should we write unit tests for CSS edge cases like this?
- Should we start using variables for z-indexes within `_control-group.scss`? (I think so)

### CODE REVIEW

**Comment by cmslewis** [comment]
Ah, found one last little bug that arises when hovering on neighbors of focused buttons:

image

This also manifested itself with the numeric input. Will push a fix momentarily.

**Comment by llorca** [comment]
Very cool 🎉  That last bug is something expected. Mouse interactions take precedence on keyboard interactions.

Can you show what your examples look like in dark theme? I suspect we'll have to make some adjustments there

**Comment by cmslewis** [comment]
@llorca whoops, just saw your comment and had already pushed fixes to keep the focus outline on top. How do the new GIFS look? The new behavior of keeping focus outlines always on top actually feels better to me, but happy to defer.

**Comment by llorca** [comment]
@cmslewis now there are issues in both light and dark theme with focus non-intent buttons being on top of intent buttons

**Comment by cmslewis** [comment]
@llorca - yes, that's what I'd expect. Feels weird to have a focus state underneath another element no matter the intent of either, no? Let's sync up in the office tomorrow.

**Comment by llorca** [comment]
This is actually still a WIP, definitely not merging today

**Comment by cmslewis** [comment]
@llorca - Whoops, thought this PR contained our new work, and I renamed it incorrectly. I'll close this PR and open a new one with the improved z-index corrections.

**Pull request closed without merging**
