### PR TITLE
`react-transition-group` is no longer externalized

### PR DESCRIPTION
**Pull request by thasner**
https://github.com/palantir/blueprint/commit/a866049f956eb416bc65bec96537985267e61b58

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/blueprint](https://github.com/palantir/blueprint), @thasner! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by adidahiya** [comment]
making something a "regular" dependency is not directly related to externalization. you can see this module is still being externalized in webpack-build-scripts: https://github.com/palantir/blueprint/blob/4b3e69c5600ec5251ae33637ae90302dd22ee9de/packages/webpack-build-scripts/externals.js#L32

**Comment by thasner** [comment]
@adidahiya if BP is externalizing these libs, why would BP remove the peer dependency?

**Comment by adidahiya** [comment]
By "remove the peer dependency", I assume you mean "change it to a regular dependency". It was done in response to this comment: https://github.com/reactjs/react-transition-group/issues/32. Multiple versions of react-transition-group can be installed, but multiple versions of React should not. I guess that means we don't need to externalize react-transition-group really. But the UMD modules are not an important part of this library; they were just added for convenience for environments like Code Sandbox. We don't use them in any production software.

**Pull request closed without merging**
