### PR TITLE
Remove color rule from icon classes

### LINKED ISSUE #437: Remove default icon color
Icons have a color specified in every context. It has caused some trouble in a few places, for instance when displaying text with a custom color (e.g. green or red) and adding an icon to it, the icon would remain grey.

Note that this change would make icons slightly darker since they'd follow the default body text color.

@pkwi what do you think about this change?

### PR DESCRIPTION
**Pull request by llorca**
#### Changes proposed in this pull request:

- Remove `color` rule from icon classes
- Adjust icon colors in input groups and dark tree items

This way, folks using a custom element with a custom `color` won't have issues with icons showing up gray.

### CODE REVIEW

**Comment by giladgray** [comment]
got one!
image

**Comment by cmslewis** [comment]
Love love love this little change. The original introduction of default icon colors bit me on a project in the past.

**Comment by cmslewis** [comment]
@llorca did you want to keep the muted icon color for the *Icons* section of our docs? It now looks like this:

image

I don't feel strongly either way.

**Comment by giladgray** [comment]
@llorca are you going to fix the toast + Icons list colors?

**Pull request merged**
