### PR TITLE
[core] feat(NumericInput): add `leftElement` prop

### LINKED ISSUE #5051: Allow adding a leftElement to a NumericInput (Blueprintjs 4.0.0-beta.10)
Please allow adding a `leftElement` to a `NumericInput`!
(Blueprintjs 4.0.0-beta.10)

### PR DESCRIPTION
**Pull request by alex-c**
#### Fixes #5051

Hello, I created this **draft** PR, as I would like to fix #5051, but I have trouble building the project on Windows (see #4221) and am not sure what I should add in the ways of tests.

- I added the necessary change and added an example to the docs. While I cannot run `yarn verify` (see above), `yarn compile` and `yarn lint` run fine. The change seems to work fine (see screenshot at the bottom).

- I am also not sure what/how much I should do in the ways of tests. So far, there are no tests for `NumericInput` at all, as far as I can see... Nor are there for `InputGroup`?

#### Checklist

- [x] Includes tests
- [x] Update documentation

#### Changes proposed in this pull request:

Add `leftElement` as an alternative to `leftIcon` for `NumericInput`, the same way it is for `InputGroup`. Since `NumericInput` uses `InputGroup`, the `leftElement` prop can just be passed down.

#### Reviewers should focus on:

`leftElement` should be working for `NumericInput`.

#### Screenshot

The following screenshot is from the example I added to the docs. Setting a button with a popover in `leftIcon` breaks the layout. With `leftElement` it works fine:

image

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/blueprint](https://github.com/palantir/blueprint), @alex-c! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by adidahiya** [comment]
Sorry about the trouble building the project in Windows.

Generally I advise running the individual build scripts in each package for the best debugging experience. For example:

```
cd packages/core
yarn compile
yarn lint
yarn test
```

It looks like you've managed to trigger the CI build successfully, though, so you should get build & test results here within a few minutes of pushing your commits.

There are actually quite a few tests for NumericInput: https://github.com/palantir/blueprint/blob/develop/packages/core/test/controls/numericInputTests.tsx

I'll review this PR soon!

**Comment by alex-c** [comment]
Oh, I guess I only looked for tests in the [forms](https://github.com/palantir/blueprint/blob/develop/packages/core/test/forms) directory. I'll take another look and see if I can add some meaningful tests.

**Comment by alex-c** [comment]
I have now added two basic test cases.

**Review by adidahiya — APPROVED** [review]
[docs preview here](https://output.circle-artifacts.com/output/job/ad1a8838-c92d-4b06-9aa7-59f469459929/artifacts/0/packages/docs-app/dist/index.html#core/components/numeric-input)

nice, this looks great! thanks for the PR, I appreciate the new option added to the NumericInput example in the docs.

**Pull request merged**
