### PR TITLE
Fix typo, `query` should be `querySelector`

### PR DESCRIPTION
**Pull request by ysmood**
Fix a typo

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/blueprint](https://github.com/palantir/blueprint), @ysmood! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by giladgray** [comment]
@ysmood this is not a typo, it's a [method from the DOM Level 4 spec](https://www.w3.org/TR/2015/WD-dom-20150428/#elements), which we polyfill via a little library called [`dom4`](https://github.com/palantir/blueprint/blob/master/packages/core/package.json#L10).

What prompted this proposal? The `query` method is [used many times](https://github.com/palantir/blueprint/search?utf8=%E2%9C%93&q=document.query%28) throughout the codebase with no trouble. Was this one giving you some issues? Did you install `@types/dom4`?

**Comment by ysmood** [comment]
For example, if I only want require part of the code base instead of require the whole project at once.

```js
let { Alert } = require('@blueprintjs/core/dist/components/alert/alert');
```

This code won't require `dom4`.

As your components grows, people normally don't won't to require the whole project.

**Comment by adidahiya** [comment]
At this stage, dom4 is a hard requirement for our components. You _can_ import specific components without pulling in everything, but you will need some core dependencies like dom4 and normalize.css (they're small packages anyway). We are potentially looking into making blueprint work without dom4 (slightly related: https://github.com/palantir/blueprint/issues/131), but I wouldn't recommend that yet.

Overall, it doesn't make sense to only move one `querySelector` usage to `query` in this PR; if we made that change, it should be holistic.

**Comment by ysmood** [comment]
@adidahiya Sure, I will close this PR, but the problem behind it still remainds, hope you can reduce these overheads.

**Comment by giladgray** [comment]
for the record, all you need is one `import "dom4"` _anywhere_ in your app (before importing individual components) to bring in the polyfill.

**Comment by adidahiya** [comment]
What exactly is the problem @ysmood? You would like blueprint to reduce external dependencies? This isn't a trivial task; there's a reason we picked dom4 to get consistent cross-browser DOM manipulation behavior. If you can come up with a thorough proposal that ensures our current level of browser compatibility, I'd be open to it, but otherwise it's not a high priority for us right now.

**Comment by adidahiya** [comment]
As far as adding an `import "dom4";` line to every component... that sounds unscalable. I would prefer to have side-effectful imports all exist together in one place at the top level of an application.

**Comment by ysmood** [comment]
Yes. The problem becomes what is the best practice to use blueprint's components separately.

At least it should be documented in the quick start tutorial. 

To import peer dependencies is a little bit ugly though.

**Comment by ysmood** [comment]
All components should require what they need, global import is not a good way for the long future.

**Comment by ysmood** [comment]
You don't have to add it to every component. I checked your code, only a few of files will need this line.

**Comment by gregtillbrook** [comment]
Incidentally, this issue just tripped me up following patching of blueprint so I could do SSR. Was really scratching my head until I figured out it was a dom4 issue.

**Pull request closed without merging**
