### PR TITLE
[Table] Frozen rows & columns

### LINKED ISSUE #503: Feature request: Add a sticky columns for the table component
Hey guys!
Honsetly, your table is one of the best components I saw for react, it has really almost everything.

I really wanna use it, but the only problem I have is that it does not support sticky columns

sticky columns: Columns that stick to the left/right of the table and while dragging the x-axis, it stays in it's place.

I would like to know if you guys having this feature in your minds, and if not I would like to know if you will considerate having the feature in the future.

If not, I would like to get an advice of how to achieve this one in your table components.
Thanks!

---

edit by @adidahiya:

tags for searchability: fix, fixed, freeze, frozen

### LINKED ISSUE #957: [Table] Can't scroll on header cells
The table won't scroll if you're over the header cells - row or column. 
Unintuitive to users and feels broken

### PR DESCRIPTION
**Pull request by cmslewis**
#### Checklist

- [x] Include tests
- [x] Update documentation

#### Changes proposed in this pull request:

- 🎉  __NEW__ `Table` now supports frozen rows & columns!
    - Set `numFrozenRows={m}` to freeze the `m` topmost rows.
    - Set `numFrozenColumns={n}` to freeze the `n` leftmost columns.
- Includes:
    - Tests
    - Documentation
    - Example

#### Reviewers should focus on:

Please test the heck out of this in the dev preview with every combination of features you can find.
- **_Reordering_** should work as expected.
- **_Resizing_** should work as expected.
    - _(though we had to move the resize handle a couple pixels to the left to make it work elegantly; see #1386 for details)_
- **_Selection_** should work as expected.
    - _(if you drag-select from a frozen pane to a non-frozen area or vice versa, the selection stretches appropriately without changing the table's scroll position)_
- **_Truncation_** should work as expected.

Things to note:
- There are some known, minor visual regressions that @llorca and I have agreed to fix in future work (tracked in #1444).
- One unit test started failing (in `formatsTests.tsx`) even though the component being tested (`TruncatedFormat`) did _not_ change. Changed the test to make it pass (see #1439 for the discussion).

#### Screenshot

_With `numFrozenRows={2}` and `numFrozenColumns={2}`:_

Docs:

image

### CODE REVIEW

**Comment by cmslewis** [comment]
Writing docs now!

**Comment by llorca** [comment]
The scrolling 🏆 🔥 🏆

**Comment by llorca** [comment]
The only weird thing I'm noticing is a persistent blue line when selecting the first non-frozen column/row, i.e. row 3 here (I have 2 frozen rows, selected row 3, scrolled after): image

With row 4, no problem:
image

**Comment by cmslewis** [comment]
Caught up IRL with @llorca, but for the record, that visual issue is already tracked in #1444.

**Comment by cmslewis** [comment]
Didn't squash because the squashed commit would have been unwieldy to look at, and the component commits were fairly self-contained.

**Pull request merged**
