### PR TITLE
Migrate to dart-sass

### LINKED ISSUE #4032: Compilation issue with newer version of SASS
When trying to import to blueprint using SASS, error is encountered.

#### Environment
- __Package version(s)__:
  - @blueprintjs/core: 3.24.0
  - webpack: 4.42.1
  - sass: 1.26.3
  - sass-loader: 8.0.2
- __Browser and OS versions__:  MacOS Catalina 10.15.4

#### Steps to reproduce

1. Create a SASS file and add `@import "~@blueprintjs/core/src/blueprint";`
2. Try compiling it using webpack.

#### Actual behavior

```
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: compound selectors may no longer be extended.
Consider `@extend .bp3-menu-item, :hover` instead.
See http://bit.ly/ExtendCompound for details.

   ╷
19 │       @extend .#{$ns}-menu-item:hover;
   │               ^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  node_modules/@blueprintjs/core/src/components/menu/_submenu.scss 19:15  root stylesheet
```

#### Expected behavior

There should be no error.

### LINKED ISSUE #4751: Sass: DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0
#### Environment

- __Package version(s)__: 3.45.0
- __Operating System__: Linux
- __Browser name and version__: N/A

#### Code Sandbox

N/A (Build warnings)

#### Steps to reproduce

1. Use latest version of `sass` (1.34.1)
2. Run a code build
3. Notice many warnings in the output

#### Actual behavior

Output receives a lot of deprecation warnings, e.g:
```
DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($pt-grid-size, 3)

More info and automated migrator: https://sass-lang.com/d/slash-div

    ╷
180 │ $pt-border-radius: floor($pt-grid-size / 3);
    │                          ^^^^^^^^^^^^^^^^^
    ╵
    node_modules/@blueprintjs/core/lib/scss/variables.scss 180:26  @import
    root stylesheet
```

#### Expected behavior

No warnings during build

#### Possible solution

Running migrator as stated in the output

### PR DESCRIPTION
**Pull request by pgoldberg**
#### Changes proposed in this pull request:

- Migrate from `node-sass` to `dart-sass`
- Run sass-migrator to replace `/` division operators with `*` or `math.div()` where appropriate

#### Reviewers should focus on:

No regressions

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/blueprint](https://github.com/palantir/blueprint), @pgoldberg! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by adidahiya** [comment]
Looks like you made some good progress here. I'm bumping stylelint & stylelint-config-palantir in https://github.com/palantir/blueprint/pull/5217, so you should get lint passing after that merges.

**Comment by adidahiya** [comment]
New stylelint config has a bug, see https://github.com/palantir/stylelint-config-palantir/issues/58. I've worked around it with a config override for now.

**Comment by adidahiya** [comment]
preview builds: [docs-app](https://output.circle-artifacts.com/output/job/770ce905-b1dc-4107-8417-df9fb5408883/artifacts/0/packages/docs-app/dist/index.html), [demo-app](https://output.circle-artifacts.com/output/job/770ce905-b1dc-4107-8417-df9fb5408883/artifacts/0/packages/demo-app/dist/index.html)

**Comment by adidahiya** [comment]
There's a bug in menu items that have submenus, probably related to the `@extend` change. This text shouldn't have an underline:

image

also, the docs-wide search omnibar isn't highlighting results as expected (the JS functionality still works, but the styles have regressed):

**Comment by pgoldberg** [comment]
Fixed those in the last commit, although it's not nearly as nice as just extending the compound selectors

Tested with dark mode and intents (comparing against blueprintjs.com) to confirm it still works correctly in those circumstances

[docs-app](https://output.circle-artifacts.com/output/job/62fb32e8-2fa0-428e-b436-9d88c4a518d9/artifacts/0/packages/docs-app/dist/index.html)

image

fixed search

**Review by adidahiya — APPROVED** [review]
nice, the menu item styles mixin implementation looks good :+1:

**Pull request merged**
