### PR TITLE
[docs] enlarge code font size in props tables

### PR DESCRIPTION
**Pull request by giladgray**
followup from #642

### CODE REVIEW

**Comment by llorca** [comment]
Looks so good!

Have we lost some of those tags in a few places? This for instance:
screen shot 2017-02-09 at 4 14 17 pm

**Comment by giladgray** [comment]
that one's not actually required

**Comment by llorca** [comment]
What do you mean? Is it some kind of leftover wording that we need to update?

**Comment by giladgray** [comment]
yep that's what it is

**Pull request merged**
