### PR TITLE
Include tabIndex for date picker shortcuts

### PR DESCRIPTION
**Pull request by rherms**
#### Changes proposed in this pull request:
This ensures event.relatedTarget is properly populated when the date input box is blurred by clicking on the date picker popover shortcuts.

### CODE REVIEW

**Comment by adidahiya** [comment]
[docs preview](https://circleci.com/gh/palantir/blueprint/28277/artifacts/0//home/circleci/project/packages/docs-app/dist/index.html)

**Comment by adidahiya** [comment]
code change seems fine, just want to confirm that this the behavior you were trying to achieve? what exactly was the bug here?

**Comment by rherms** [comment]
I just wanted event.relatedTarget to be populated for the onBlur handler of the DateInput component.

**Comment by adidahiya** [comment]
publishing now as 3.15.1

**Pull request merged**
