### PR TITLE
Fix typo in tooltip documentation

### PR DESCRIPTION
**Pull request by markhepburn**
Very minor change

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/blueprint](https://github.com/palantir/blueprint), @markhepburn! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by giladgray** [comment]
@markhepburn please sign the CLA when you have a chance and we'll get this merged and shipped!

**Comment by markhepburn** [comment]
@giladgray No problem; the cla site is timing out for me at the moment (is it still https://cla.palantir.com?), but when I notice it's back up I'll run through that. 👍

**Comment by giladgray** [comment]
@markhepburn 🤔 CLA site seems to load properly now. we are in the process of preparing the release so if you can close this out ASAP, we can get it in 1.34.0

**Comment by markhepburn** [comment]
@giladgray done!

**Comment by adidahiya** [comment]
This will be in the next patch release.

**Pull request merged**
