### PR TITLE
[WIP] Dropdown component is a simple <select>

### PR DESCRIPTION
**Pull request by giladgray**
## ⚠️ 🚒  _wow such a work in progress_ 🚚  ⚠️ 

thanks @adidahiya for building out most of this during winter hack week!

this is a great scaffold upon which to build the mythical `Dropdown` component.

proposed additional props:

- ✅  `filterItem` to customize the filtering algorithm itself (naming help needed)
- ✅  `items` accepts `IDropdownMenuItemProps[]` __or__ map of group names to array? instead of current `default` key.
- `noResultsRenderer` to customize No Results item

additional features:

- keyboard support, obvs
- clear button

### CODE REVIEW

**Comment by llorca** [comment]
This is great! Would be so neat to have a custom search and target renderer... It would solve all of our typeahead problems. For instance, this typeahead example inside a dropdown with input field and results below is one use case. Other very common use cases I've seen:
- input field trigger, with a separate popover for results (similar to react-select)
- a list of files inside a side panel, with a search field at the top. The field filters down the list

**Comment by giladgray** [comment]
i think there are two components to build:
1. `Dropdown`, which we have here: some target shows an optionally filterable list in a popover
2. `TypeAhead`: typing in an input shows a filtered list in a popover

i see these two as distinct interactions with different enough patterns to warrant two components. the components will be relatively simple, essentially just composing the smaller pieces.

so let's not worry about the "input field trigger" just yet.

**Comment by llorca** [comment]
Hmm, can you elaborate on the distinct interactions? I don't see it. I see one interaction: you type into a field to filter down a list. The fact that the list is in a popover or not is a simple visual difference -- it doesn't change the interaction.

**Comment by llorca** [comment]
The interesting part in your `Dropdown` description is the "optionally filterable list" for sure. The fact that it's in a popover is also a detail

**Comment by giladgray** [comment]
the main difference is _where_ you type. in `Dropdown` you _only_ type inside the `Popover`, whereas in `TypeAhead` you never (and can't) type inside the `Popover`.

**Comment by tgreenwatts** [comment]
Am I getting this right?

Typehead example: 
image
Dropdown example:
image

**Comment by giladgray** [comment]
@tgreenwatts _¡precisamente!_

**Comment by llorca** [comment]
It sounds like both of the components you mention are the same thing, do the same logic, with the exception that the rendered thing looks different. The _where_ as you call it out shouldn't matter to Blueprint, that's a detail for the consumer to worry about. The thing that's extremely valuable for a consumer is the ability to have a defined input filter a list, whatever the details of the layout are.

You mentioned that filtering substrings is super easy, then I could see consumers doing it themselves, and the rendering is just a composition of input, popover, whatever else they need? I see these two components as convenience components. I'm not convinced this belongs in core. What belongs in core is the in-between, the pieces that are common to these two components. I believe the challenge here, and the most useful thing we could do for our users, is to extract those generic pieces

**Comment by adidahiya** [comment]
I feel pretty strongly that this should be in the collection of core components. Blueprint should have a ready-to-use replacement for the HTML `<select>` element.

**Comment by leebyp** [comment]
I agree the filtering piece is trivial but the biggest reason I can see this being in core is actually a) the keyboard interactions and b) the selection states. As the component develops, things like async loading will inevitably come up, which furthers that case.

As to both the proposed `Dropdown` and `Typeahead` doing the same thing, they can be wrapped into different components but both utilize the same code underneath to ensure consistency. However, if it does turn out the difference are minimals props then we should consider merging. Currently I can only think of `closeOnSelect` and `showFilter` and the different child elements of the `Popover` but I'm sure I'm missing something.

**Comment by llorca** [comment]
- Why do we need a `<select>` replacement? `<select>` is performant, has full keyboard and accessibility support. It's just fine, I don't see why we need to reinvent the wheel here. Again, one of the major interesting pieces is the filtering and how we can make it generic. That's what we don't have, and that's the key here.

- Can you elaborate on selection states? Keyboard interactions are obviously a must-have, but it has nothing to do with either of these components. More like a `Menu`/`MenuItem` matter. Totally generic and unrelated to a dropdown or a typeahead as proposed above.

- I still don't buy that such a simple composition of an input with a popover or whatever else is worth having these 2 convenience components. I don't believe it's in Blueprint's interest to provide this through core: remember, we're building a **system of composable atomic pieces**. The goal of core isn't to provide a bunch of opinionated molecules. We should instead think about the best way to expose the reusable, atomic interactions that convenience components such as `Dropdown` would leverage

**Comment by adidahiya** [comment]
@llorca those are fair points. Where does that leave components like `NumericInput` and `DateInput`, which feel more like opinionated molecules? The line is not always so clear.

The main reason I want to replace `<select>` is visual design & filtering functionality. Right now everyone relies on react-select for this and I want to provide an alternative that will work in most (>70%) of the current use cases __and is fairly ergonomic__ (read: requires little application-side code).

Let's sync up offline with @giladgray to follow up on this discussion

**Comment by giladgray** [comment]
closing for now until we're ready to pick this up again.

**Pull request closed without merging**
