### PR TITLE
[core]fix(Dialog): add margin to dialog footer actions (#3848)

### LINKED ISSUE #3848: DIALOG_FOOTER_ACTIONS missing margin
#### Environment

- __Package version(s)__: @blueprintjs/core@3.20.0
- __Browser and OS versions__: Chrome 78.0.3904.97, MacOS 10.14.6

If possible, link to a minimal repro (fork [this code sandbox](https://codesandbox.io/s/blueprint-sandbox-et9xy)): https://codesandbox.io/s/blueprint-sandbox-5nfn7

#### Steps to reproduce

1. Add div with class DIALOG_FOOTER_ACTIONS inside Dialog component

#### Actual behavior

Margin of footer actions content should be aligned with dialog

#### Expected behavior

There are no margins in DIALOG_FOOTER_ACTIONS

#### Possible solution

Set common dialog margin on DIALOG_FOOTER_ACTIONS

### PR DESCRIPTION
**Pull request by IvanBaranov**
#### Checklist

- [ ] Includes tests
- [ ] Update documentation

#### Changes proposed in this pull request:

Added margin to DIALOG_FOOTER_ACTIONS

#### Screenshot

Screenshot 2019-11-18 at 23 56 35

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/blueprint](https://github.com/palantir/blueprint), @IvanBaranov! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by IvanBaranov** [comment]
I forgot do disable CircleCI on my fork, do I need to create a new pull request to pass checks?(currently checks fail because of [#3660](https://github.com/palantir/blueprint/issues/3660)

**Comment by adidahiya** [comment]
No, your test failure is a different flake. I just tried retriggering the CI workflow

**Comment by adidahiya** [comment]
not a bug, see my comment on the original issue

**Pull request closed without merging**
