### PR TITLE
[core] Add missing invoke in checkbox component

### LINKED ISSUE #2370: Checkbox component does not work in controlled mode
### Bug report

blueprintjs/core: 2.1.1,
Browser: Google Chrome | 65.0.3325.181 (Official Build) (64-bit)
OS: macOS Sierra 10.12.6 (16G1314)

#### Steps to reproduce

1. Use `Checkbox` component
2. Add `checked` and `onChange` property
3. Click on component

#### Actual behavior

Checkbox change indicator but `onChange` does not invoke

#### Expected behavior

Checkbox should invoke `onChange` when click on component happend

#### Example code
```
import React, {Component} from 'react';
import {Checkbox} from '@blueprintjs/core';

class Test extends Component {
    constructor(props) {
        super(props);
        this.state = {
            isChecked: false
        };
    }

    handleEnabledChange() {
        this.setState({isChecked: !this.state.isChecked});
    }

    render() {
        return (
            <Checkbox
                checked={this.state.isChecked}
                label={this.state.isChecked ? 'Checked' : 'Unchecked'}
                onChange={this.handleEnabledChange}
            />
        );
    }
}

export default Test;
```
#### Note
I am not sure but probably this [change](https://github.com/palantir/blueprint/pull/2323/commits/6c8a29f65053310ee5bc399c7459d4f4dc379c78#diff-c3a6a2b0fe2f0ed4fefa920240aeb9f4R177) is cause this issue

### PR DESCRIPTION
**Pull request by js-um**
#### Checklist

- [x] [Enable CircleCI for your fork]

### CODE REVIEW

**Comment by giladgray** [comment]
thanks @js-um! please sign the CLA so we can merge this.

**Comment by js-um** [comment]
@giladgray I signed CLA 19 hours ago in cla.palantir.com, but it has not been processed yet. do I need additional process?

**Comment by giladgray** [comment]
@js-um try it again perhaps? this doesn't happen often. you can also try pushing an empty commit to refresh the build, but i'm not sure that'll have any effect.

**Comment by giladgray** [comment]
hooray! glad to know that works.

**Pull request merged**
