### PR TITLE
[v4] [core] fix(MenuItem): improve interactive styles

### LINKED ISSUE #4985: [v4] MenuItem active + hover state styling looks off
#### Environment

- __Package version(s)__: core v4.0.0-beta.5, select v4.0.0-beta.5
- __Operating System__: macOS
- __Browser name and version__: Chrome

#### Steps to reproduce

1. [Visit v4 select docs](https://blueprintjs.com/docs/versions/4/#select/select-component)
1. Select an item in dropdown
1. Open the dropdown again, hover through items

#### Actual behavior

The active MenuItem goes from dark bg -> light bg, kind of an unexpected interaction:

#### Expected behavior

??

#### Possible solution

Use a slightly lighter or darker bg, but don't invert the colors when hovering over an active MenuItem

### PR DESCRIPTION
**Pull request by adidahiya**
#### Checklist

- [ ] Includes tests
- [x] Update documentation

#### Changes proposed in this pull request:

- Update MenuItem colors to match the intended v4 designs
- Move MenuItem "modern colors" style overrides into the default style code in `components/menu/`

#### Reviewers should focus on:

- All the different states & props for MenuItem (see new example)
- Select dropdown interactions
- MultiSelect dropdown interactions

### CODE REVIEW

**Comment by aycai** [comment]
I think this makes the most sense in the `select` context where the `MenuItem` changes to blue when selected. That said, selected states should include something else like an icon regardless, so this works on its own.

**Comment by aycai** [comment]
Caught a visual nit - text of root MenuItem changes to default text
Screen Shot 2021-10-27 at 1 26 32 PM
:
Screen Shot 2021-10-27 at 1 25 13 PM

**Comment by adidahiya** [comment]
Fixed styles when submenus are open:

**Comment by adidahiya** [comment]
slight regression in custom icon placement:

image

**Pull request merged**
