### PR TITLE
[core] Callout uses h4, fix icon vertical alignment

### PR DESCRIPTION
**Pull request by giladgray**
@pkwi Dialog title also uses an h5. should I change that one too?

### CODE REVIEW

**Comment by llorca** [comment]
@giladgray yessir. looks like we need to update the html markup of callouts in docs?

**Comment by giladgray** [comment]
@llorca would you be able to pick this work up? changing all the `h5`s to `h4`?

**Comment by llorca** [comment]
done!

**Comment by giladgray** [comment]
@llorca test failures. probably need to update a selector.

**Pull request merged**
