### PR TITLE
Prepare Release 1.16.0

### PR DESCRIPTION
**Pull request by giladgray**
:fireworks: **Highlights**: colored icons, `DateInput` `inputProps`, `Table` arrow key scrolling

:book: **Latest docs**: [blueprintjs.com/docs](http://blueprintjs.com/docs)

## General
- We now develop against React 15.5.1 for the latest hotness! Peer dependency versions have not changed.
## @blueprintjs/core `1.16.0`
- 🌟  __NEW__ support `.pt-intent-*` modifiers on the icon classes `.pt-icon`, `.pt-icon-standard`, `.pt-icon-large` #1019
image
- __NEW__ three UI icons: `blocked-person`, `slash`, `percentage` #1018 
- __Fixed__ `.pt-control-group` creates a new stacking context to isolate z-indices of its controls #700 
- __Fixed__ React PropTypes deprecation warning #991 

## @blueprintjs/datetime `1.14.0`
- 🌟 __NEW__ `DateInput` `inputProps` prop just like `DateRangeInput` #387, #1010 
- ⚠️ React PropTypes warning #991 is still present in `datetime` package due to `react-day-picker` dependency being out-of-date. PR to fix this is blocked on typings #1014 

## @blueprintjs/table `1.13.0`
- 🌟 __NEW__ auto-scroll the viewport when moving focused cell with arrow keys! #915

- __Fixed__ Truncated cell icons appear when expected (regression in 1.12.0) #1022 
- __Fixed__ `Table` auto-resize columns (by double-clicking on edge) correctly computes header width #952 
- __Fixed__ deprecation warning from `Popover` #1012 

## Documentation
- __NEW__ Add `?examples` query string to URL to hide all text and tables, leaving only CSS and React examples #1020, #125 
  - This is meant primarily for development and testing, not presentation, so text-heavy pages can look pretty awkward
  - Try it out for the [Buttons page](http://blueprintjs.com/docs/?examples#core/components/button)

### CODE REVIEW

**Comment by adidahiya** [comment]
let's just omit `@blueprintjs/docs` if it's unchanged

**Comment by tgreenwatts** [comment]
Is it worth using the word "Regression" when describing the pure issue - make it clear that it was present only in 1.12.0?

**Comment by giladgray** [comment]
@tgreenwatts i wondered the same thing actually

**Comment by giladgray** [comment]
release notes updated on both counts

**Comment by cmslewis** [comment]
Was trying to verify the `pt-icon` intent coloring change, and after a few minutes of observing that it wasn't working, found this specificity override:

image

Would be awesome to add an intent dropdown to the icons page that can change the intents easily and just generally communicate that this feature exists.

**Comment by giladgray** [comment]
meh not worth it. would be much easier to add a CSS example with modifier table, but i still don't think it's necessary. it's just enough that it work.s

**Comment by tgreenwatts** [comment]
Looks great to me :shipit:

**Comment by cmslewis** [comment]
@giladgray nice note about icon intents 👍

**Pull request merged**
