### PR TITLE
[datetime] feat(DateInput): add fill prop

### LINKED ISSUE #751: Support `pt-fill` in new components
- [ ] DateInput
- [x] NumericInput
- [x] file upload

### PR DESCRIPTION
**Pull request by nathanchrs**
#### Checklist

- [x] Includes tests
- [x] Update documentation

#### Changes proposed in this pull request:

Add `fill` prop to DateInput which is forwarded to the contained Popover.

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/blueprint](https://github.com/palantir/blueprint), @nathanchrs! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by adidahiya** [comment]
[docs preview](https://circleci.com/gh/palantir/blueprint/27721/artifacts/0//home/circleci/project/packages/docs-app/dist/index.html)

**Comment by adidahiya** [comment]
this change looks ok, but there's a problem with the current example styling:

image

it's not centered because of the margin around the input. I think we should add special styling to this example to make it look good. I'd rather not change the general docs example styles because they generally look fine. users can choose to add margin themselves if they enable this new prop on DateInput components. add some styles here: https://github.com/palantir/blueprint/blob/793a1777f558355521541f4c18b17fbf0a51b5e2/packages/docs-app/src/styles/_examples.scss#L488

```scss
#{example("DateInputExample")} {
  .docs-example > * {
    margin: 0 0 20px 0;
  }
}
```

**Comment by nathanchrs** [comment]
I have fixed the example style, but apparently the build now fails on an unrelated problem. I'll check it later today.

**Comment by adidahiya** [comment]
the new build failures are unrelated, due to #3799. i'm looking into it

**Pull request merged**
