### PR TITLE
Stepper

### PR DESCRIPTION
**Pull request by justinbhopper**
Adds a new components `Stepper`, `Step`, and `StepConnector`.  A stepper is a wizard-like progress indicator.  

**This PR is not complete** due to an [issue with compiling docs-data](https://github.com/palantir/blueprint/issues/3062#issuecomment-439363356) on a windows machine.  

I added an example and started work on the docs page, but all of this was done blindly and very may have issues.  Help is very much appreciated.

#### Screenshot

remarkable ai (1)

### CODE REVIEW

**Comment by justinbhopper** [comment]
Apparently I have some linting issues too, but running `npm run lint` is producing an error for me, perhaps due to using windows.  Having trouble understanding what the build's linting errors are suggesting I fix.

```
F:\Workarea\Sandboxes\blueprint> lerna run lint:es --scope @blueprintjs/docs-app                                                     lerna notice cli v3.20.2
lerna info versioning independent
lerna notice filter including "@blueprintjs/docs-app"
lerna info filter [ '@blueprintjs/docs-app' ]
lerna info Executing command in 1 package: "yarn run lint:es"
lerna ERR! yarn run lint:es exited 1 in '@blueprintjs/docs-app'
lerna ERR! yarn run lint:es stdout:
yarn run v1.13.0
$ es-lint
[node-build-scripts] Using ESLint ignore file path F:\Workarea\Sandboxes\blueprint\.eslintignore
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

lerna ERR! yarn run lint:es stderr:
events.js:200
      throw er; // Unhandled 'error' event
      ^

Error: spawn eslint ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn eslint',
  path: 'eslint',
  spawnargs: [
    '--color',
    '-f',
    'codeframe',
    'C:\\Program Files\\nodejs\\node.exe',
    'F:\\Workarea\\Sandboxes\\blueprint\\packages\\node-build-scripts\\es-lint.js',
    '--ignore-path',
    'F:\\Workarea\\Sandboxes\\blueprint\\.eslintignore',
    'F:\\Workarea\\Sandboxes\\blueprint\\packages\\docs-app\\{src,test}\\**\\*.{ts,tsx}'
  ]
}
error Command failed with exit code 1.

lerna ERR! yarn run lint:es exited 1 in '@blueprintjs/docs-app'
```

**Comment by justinbhopper** [comment]
Closing PR - will open a new one with fixes in place.

**Comment by adidahiya** [comment]
@justinbhopper before you do, can you please open an issue to discuss your API design and feature proposal? We usually don't add big new features to Blueprint like this without a proposal review process. Note that this component has been rejected in the past since we don't really use this design pattern at Palantir, but I'd be open to reconsidering.

**Comment by justinbhopper** [comment]
@adidahiya Of course, I'd be happy to.  This was mostly an exercise for me to get the builds working on windows, which I succeeded in doing after some effort.

**Pull request closed without merging**
