### PR TITLE
[core] fix(Toast): add alert role to toast message for a11y

### LINKED ISSUE #5324: add role="alert" to toast messages for better a11y
#### Environment

- __Package version(s)__: 4.3.2
- __Browser and OS versions__: All

#### Feature request

add `role="alert"` to toast messages for a11y purposes.

### PR DESCRIPTION
**Pull request by bvandrc**
#### Checklist

- [N/A] Includes tests
- [N/A] Update documentation

add `role="alert"` to toast message for a11y purposes.

### CODE REVIEW

**Comment by bvandrc** [comment]
issue https://github.com/palantir/blueprint/issues/5324

**Comment by adidahiya** [comment]
I think this should only be applied to the toast message, according to the [docs](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/alert_role):

> The alert role should only be used for text content, not interactive elements such as links or buttons.

**Comment by bvandrc** [comment]
> I think this should only be applied to the toast message, according to the [docs](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/alert_role):
> 
> > The alert role should only be used for text content, not interactive elements such as links or buttons.

updated. or would you prefer to kill this PR and have the user pass say, `<span role="alert">Users Message</span>` as the `message` themselves?

**Review by adidahiya — APPROVED** [review]
lgtm

**Pull request merged**
