### PR TITLE
[Resources] Sketch file update

### LINKED ISSUE #2668: Update Sketch design resources in Documentation
The sketch file in docs is outdated by two years

* The 2017 visual style now deviate from the current look of Blueprint
* Sketch now supports Libraries and it will be great idea to provide it as a Library
* New components and icons are missing from the Sketch file

Thank you.

### PR DESCRIPTION
**Pull request by pkwi**
#### Fixes #2668 

Added new components and updated visual styles. Symbols coming in the next few weeks.

### Change log

**Typography**

* updated Headings sizes (font + line height)
* updated Dialog heading sizes (h5 => h4)
* added Small text styling

**Buttons**

* fixed gradient styling for Default buttons
* added small buttons with icon
* added small icon buttons - primary

**Callouts**

* updated icons
* updated Callout heading sizes (h5 => h4)

**Dropdown menus**

* fixed “Circular” icon
* fixed section headers' spacing
* fixed hover state color

**Navigation bar**

* updated header

**Lists & trees**

* fixed Empty state positioning

**Tags & badges**

* added Rounded tags example
* added Removable tags example

**Forms**

* updated button styling in File upload
* updated secondary text
* added Control group
* added Numeric input
* added Input group example

**Dialogs & alerts**

* removed divider

**Toasts**

* removed button divider

**Date picker**

* updated month and year styling
* added Action bar
* updated AM/PM selection

**Tabs**

* added vertical tabs

**Breadcrumbs**

* added breadcrumbes

**Table**

* renamed Tables > HTML tables
* added Table component

### CODE REVIEW

**Comment by romanr** [comment]
The sketch file contains non-standard fonts. The warning appears when file is opened:

image

This should be fixed before releasing.

**Comment by mulholio** [comment]
@romanr I've run into this issue and it seems strange to me. I have the official Apple SF fonts from https://developer.apple.com/fonts but Blueprint appears to have named their versions of the font differently to Apple.

In Blueprint, the fonts are named `SFUIDisplay-<weight>` and `SFUIText-<weight>`, but
for Apple, the fonts are named `SF-Pro-Display-<weight>` and `SF-Pro-Text-<weight>`.

My current solution to this is to replace each of the Blueprint-named fonts with the corresponding Apple ones. This feels a little hacky and so ideally I'd like to change the font styles to the proper Apple ones. However, I'm wary of this in case someone on the Blueprint team has made this choice for a reason. Can anyone at Blueprint elaborate on why this is happening? @pkwi ?

As for `DINNextLTW04-Medium`, I found it [here](https://github.com/setpixel/outliner/blob/master/assets/fonts/din/dinNextLTW04-Medium.ttf).

**Comment by murtagha** [comment]
qqet8jvcxutgxt0rg4rkf379cnx5hc799uzaamena3

**Comment by romanr** [comment]
@mulholio Initially Apple did not release SF fonts officially. People copied them from the SDK and used in designs.  
Later Apple officially released these fonts and when they were released they had slightly different font names as we have them now.  

So it seems to me that the case is the Blueprint sketch file was started with "old" version of those fonts.  

Designer needs to install official Apple SF fonts, uninstall unofficial SF fonts. Then open file and use "Missing fonts" dialog to update.

**Pull request merged**
