### PR TITLE
Update select-component.md

### PR DESCRIPTION
**Pull request by markdhel**
#### Checklist

- [ ] Includes tests
- [x] Update documentation

#### Changes proposed in this pull request:

Some minor update on documentation

#### Reviewers should focus on:

Some minor update on documentation

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/blueprint](https://github.com/palantir/blueprint), @markdhel! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by giladgray** [comment]
@markdhel this is a whitespace-only change that doesn't affect the rendered result at all so i'm going to close this PR. further, the line wrapping was performed automatically using https://marketplace.visualstudio.com/items?itemName=stkb.rewrap so this isn't even safe for human editing.

**Comment by markdhel** [comment]
@giladgray I don’t understand. I edited as well the `modifiers.filtered` to `modifiers.matchesPredicate` because I think `matches.filtered` is no longer available. Please correct me if I’m wrong. Thanks.

**Comment by giladgray** [comment]
hmm you know what, somehow I missed that change. will reopen and merge 👍

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/blueprint](https://github.com/palantir/blueprint), @markdhel! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by giladgray** [comment]
@markdhel would you mind signing the CLA? I cannot merge this until you do that.

**Comment by markdhel** [comment]
@giladgray signed 👍

**Pull request merged**
