### PR TITLE
[docs] API browser and "see" JSDoc tag support

### LINKED ISSUE #817: Make interfaces and components in code blocks act as links
As an example, in the following image it'd be nice if the circled sections were clickable and would redirect to the relevant sections in docs. There are many places where this would need to happen so I imagine it's a pretty huge change. Belying this enhancement request is the fact that certain interfaces, while referenced, do not exist on the docs page. Perhaps undocumented interfaces warrant a separate ticket?

screen shot 2017-03-09 at 1 50 45 pm

Marking as P3 because in most instances, the search box is sufficient if not a slightly more tedious way of getting to the same destination.

#### BP version: 1.11.1

### LINKED ISSUE #2020: [docs] all type aliases should be de-referenced
even with #1982, we still have some references that are opaque and not useful, like `TreeEventHandler`:

image

### PR DESCRIPTION
**Pull request by giladgray**
#### Fixes #817, Fixes #2020 

_(not really a breaking change, but we want to get this in for 2.0)_

#### Changes proposed in this pull request:

Known Typescript members are now links! Clicking such a link opens an API Browser dialog with full information about that member, and you can link around to other related members, or browser the entire set of known members.

#### Reviewers should focus on:

- the UI here is pretty rough. what's the minimal feature set to make this passable?

#### Screenshot

api-browser

### CODE REVIEW

**Comment by adidahiya** [comment]
looks passable enough for now.

**Comment by adidahiya** [comment]
I don't really understand how the left sidebar is useful. Why would you want to browse to other interfaces by name? Wouldn't you always just click on them from the docs? This is a weird additional navigation layer on top of the docs and I think it's confusing.

**Comment by llorca** [comment]
yeah, right now you click one from the component docs. we had plans on providing a dedicated button/page for the API docs only, which is why this dialog has a search and a list of all interfaces

**Comment by llorca** [comment]
Do we display empty interface on purpose?
image

**Comment by adidahiya** [comment]
Also string unions like `IconName` could use some visual work

**Comment by llorca** [comment]
word. maybe we just truncate for now. also noticed that `@blueprintjs/icons` doesn't link anywhere:
image

**Comment by adidahiya** [comment]
Hmm I'm still not sure about the dialog design... what if it was a sidebar on the right of the whole docs app?

a few issues:

- [ ] this interface is blank
  image
- [ ] icon name overflows the dialog and doesn't scroll

**Comment by giladgray** [comment]
Dialog is cheap design & implementation. Adding a third column is expensive on both sides.

Will fix those issues.

**Comment by adidahiya** [comment]
why is this a breaking change?

**Pull request merged**
