### PR TITLE
use normalize v7

### LINKED ISSUE #1477: Upgrade normalize

### PR DESCRIPTION
**Pull request by giladgray**
#### Changes proposed in this pull request:

Normalize v4.1.1 &rArr; v7.0.0 [changelog](https://github.com/necolas/normalize.css/blob/master/CHANGELOG.md)

manually diffed code; changes seem safe and actually includes some good fixes!

### CODE REVIEW

**Comment by adidahiya** [comment]
needs careful design review but generally :+1:

**Comment by llorca** [comment]
Going through every component now!

**Comment by llorca** [comment]
- [ ] `button.pt-button` has a font family problem: `sans-serif` instead of our custom system one. `a.pt-button` is fine

**Comment by llorca** [comment]
Everything else looks good 👍

**Pull request merged**
