### PR TITLE
Pass inputRef to <Suggest> & <MultiSelect>

### PR DESCRIPTION
**Pull request by alxmiron**
Updated #2079 PR for latest 2.0 branch

### CODE REVIEW

**Comment by alxmiron** [comment]
<h3>Pass inputRef to <Suggest> & <MultiSelect></h3>

Preview: <strong><a href='https://142-75619030-gh.circle-artifacts.com/0/home/circleci/project/packages/docs-app/dist/index.html' target='_blank'>documentation</a> | <a href='https://142-75619030-gh.circle-artifacts.com/0/home/circleci/project/packages/landing-app/dist/index.html' target='_blank'>landing</a> | <a href='https://142-75619030-gh.circle-artifacts.com/0/home/circleci/project/packages/table-dev-app/dist/index.html' target='_blank'>table</a></strong>

**Comment by alxmiron** [comment]
@giladgray Am I missing something? Why I can't get green status from compile, lint & install CI jobs? http://prntscr.com/iofkpl

**Comment by giladgray** [comment]
huh weird. @alxmiron it looks like the entire build ran green but it wasn't reported properly to github: https://circleci.com/workflow-run/5dca9b59-a108-4397-9556-8063f1b72234

try re-running it?

**Comment by alxmiron** [comment]
<h3>Pass inputRef to <Suggest> & <MultiSelect></h3>

Preview: <strong><a href='https://148-75619030-gh.circle-artifacts.com/0/home/circleci/project/packages/docs-app/dist/index.html' target='_blank'>documentation</a> | <a href='https://148-75619030-gh.circle-artifacts.com/0/home/circleci/project/packages/landing-app/dist/index.html' target='_blank'>landing</a> | <a href='https://148-75619030-gh.circle-artifacts.com/0/home/circleci/project/packages/table-dev-app/dist/index.html' target='_blank'>table</a></strong>

**Comment by giladgray** [comment]
@alxmiron test flake. re-run failed job from dropdown here https://circleci.com/gh/HiTask/workflows/blueprint/tree/am%2Fselect-input-ref
image

**Comment by alxmiron** [comment]
<h3>Pass inputRef to <Suggest> & <MultiSelect></h3>

Preview: <strong><a href='https://155-75619030-gh.circle-artifacts.com/0/home/circleci/project/packages/docs-app/dist/index.html' target='_blank'>documentation</a> | <a href='https://155-75619030-gh.circle-artifacts.com/0/home/circleci/project/packages/landing-app/dist/index.html' target='_blank'>landing</a> | <a href='https://155-75619030-gh.circle-artifacts.com/0/home/circleci/project/packages/table-dev-app/dist/index.html' target='_blank'>table</a></strong>

**Pull request merged**
