### PR TITLE
The documentation is completely broken on firefox.

### PR DESCRIPTION
**Pull request by krm35**
When you navigate in the doc, the app crashes.

#### Checklist

- [ ] Includes tests
- [x] Update documentation

#### Changes proposed in this pull request:

Just a basic check.

#### Screenshot

https://i.imgur.com/KCG74Rp.png

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/blueprint](https://github.com/palantir/blueprint), @krm35! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by krm35** [comment]
I won't sign the license agreement.

**Comment by adidahiya** [comment]
I can't repro this bug in Firefox. Can you please file an issue first and provide more details of the bug? Also I can't do much with PRs like this if you don't want to sign the CLA.

**Comment by krm35** [comment]
No problem, it seems the problem comes from an extension in my browser. Everything is fine when I disable it. Btw I don't want to fill in a KYC for a PR...

**Pull request closed without merging**
