### PR TITLE
[core] feat(Drawer): return focus to active element after closing

### LINKED ISSUE #3592: Focus back to element when drawer close
#### Environment

- __Package version(s)__: 3.15.1
- __Browser and OS versions__: Firefox, Arch Linux

#### Feature request

Focus return to calling element when opening drawer like element.

#### Examples

When the user clicks on the menu button the drawer opens and when the user presses the `esc`. the focus of the application when somewhere else rather than the menu button.
It can be better accessbility who use the keyboard.

### PR DESCRIPTION
**Pull request by adidahiya**
Fixes #3592

Difficult to test because `document.activeElement` doesn't seem to update as expected in enzyme...

### CODE REVIEW

**Comment by adidahiya** [comment]
works in Chrome & FF

**Comment by Nantris** [comment]
Is some way to disable this available? We manage focus ourselves in our app, but this change prevents us from doing that, because it immediately undoes whatever we do and focuses the last `document.activeElement`.

**Comment by Nantris** [comment]
@adidahiya is there any way to circumvent this? If you know one, it would really help us a lot!

**Comment by adidahiya** [comment]
@Slapbox no, but we can add a prop which enables this behavior, something like `returnFocusOnClose` where it's set to `true` by default

**Comment by adidahiya** [comment]
@Slapbox see https://github.com/palantir/blueprint/pull/4620

**Comment by Nantris** [comment]
Wow that was crazy fast to have a PR opened! Thanks for your attention on this @adidahiya!

**Pull request merged**
