### PR TITLE
export draggable

### PR DESCRIPTION
**Pull request by toddself**
#### PR checklist

- [x] Addresses an existing issue: #251 
- [ ] New feature, bugfix, or enhancement
  - [ ] Includes tests
- [ ] Documentation update

#### What changes did you make?

Export Draggable and IDraggableProps

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/blueprint](https://github.com/palantir/blueprint), @toddself! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by themadcreator** [comment]
hey @toddself I did nearly the same thing in my other PR. I also want to export a few more helpful interaction classes, so do you mind if i close this one in favor of #254  ?

**Comment by themadcreator** [comment]
Well I merged the other one, so closing this one.

**Comment by toddself** [comment]
@themadcreator that sounds fine with me :).  what ever gets the interface published works!

**Pull request closed without merging**
