### PR TITLE
[core] feat(Spinner): add more a11y markup, support HTML attrs

### LINKED ISSUE #5317: Spinner item does not take other props
#### Environment

- __Package version(s)__: 4.3.2
- __Operating System__: Windows 10
- __Browser name and version__: Chrome / All

#### Steps to reproduce

Trying to pass other props to the `Spinner` item, and they don't take effect. Specifically, trying to add `aria-label` to the `Spinner` item, and that prop is not being implemented.

#### Expected behavior

Ability to pass various other props to the Spinner item

### PR DESCRIPTION
**Pull request by bvandrc**
#### Checklist

- [X] Includes tests
- [N/A] Update documentation

#### Changes proposed in this pull request:

Allow custom html props to be passed to `Spinner`

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/blueprint](https://github.com/palantir/blueprint), @bvandercar-vt! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by bvandrc** [comment]
I am on Windows 10 and am getting errors when running `yarn verify`/`yarn compile`, and cannot run `yarn test`either-- can one of the Devs please check out this branch and run the test I've written plus whatever else needs to be done?

**Comment by adidahiya** [comment]
@bvandercar-vt compilation and tests look good, I got them to pass locally, and they pass in CI.

I pushed an additional commit to add more recommended `aria-` attributes according to the [MDN documentation for role="progressbar"](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/progressbar_role).

**Comment by bvandrc** [comment]
> @bvandercar-vt compilation and tests look good, I got them to pass locally, and they pass in CI.
> 
> I pushed an additional commit to add more recommended `aria-` attributes according to the [MDN documentation for role="progressbar"](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/progressbar_role).

Awesome, thanks for your help!

**Comment by adidahiya** [comment]
[docs preview build here](https://output.circle-artifacts.com/output/job/2589e18d-2c98-4528-9297-039424348dad/artifacts/0/packages/docs-app/dist/index.html#core/components/spinner)

**Review by adidahiya — APPROVED** [review]

**Pull request merged**
