### PR TITLE
fix file input button

### LINKED ISSUE #2130: Button alignment within File upload is broken
### Bug report

- __Package version(s)__: 2.0.0-rc.1
- __Browser and OS versions__: macOS 10.13.2, Safari 11.0.2 / Chrome 64.0.3282.167 / Firefox 58.0.2

#### Steps to reproduce

1. Button alignment within the input field is broken in v2.

#### Actual behavior

screen shot 2018-02-14 at 12 11 47 pm

#### Expected behavior

Button should be aligned proportionately.

### PR DESCRIPTION
**Pull request by giladgray**

### CODE REVIEW

**Comment by giladgray** [comment]
button is missing shadow for some reason???

**Comment by adidahiya** [comment]
yeah... I can repro on Chrome and FF

**Comment by giladgray** [comment]
what's not to repro, the property is missing from the CSS. it appears in blueprint.css, but not in docs-app.css so seems the prod step is stripping it, but i can't figure out why. and it works on hover. this just doesn't make any sense.

**Comment by giladgray** [comment]
well fudge, this is actually broken in all docs previews. not a regression from this PR, so i'm going to merge.

**Pull request merged**
