### PR TITLE
Date Range Input

### LINKED ISSUE #249: Feature request: <DateRangeInput/>
Same like `<DateInput/>` for DateRange , for now i used popover. but i think it is good to have it as a component

## TODOs

@cmslewis: I'll use this space to track TODOs for this component (currently living on `feature/date-range-input`).

### Part 9: Obey and control the focused field
- [x] The currently focused field dictates which end of the date range the next click will modify.
- [x] Move focus between fields intelligently after a date is selected.
- [x] Add unit tests to verify the behavior.

### Part 10: Basic documentation
- [x] Add documentation for `DateRangeInput`
    - [x] Basic description of the component (hovered range, selected range, typing, validation)
    - [x] Uncontrolled mode
    - [x] Controlled mode (add disclaimer that it isn't fully implemented yet)
    - [x] JavaScript API (props, etc. - can get this for free)
    - [x] Basic example with controls (at this point, mostly just need a `format` selector)

### Part 11: Merge `feature/date-range-input` into `master`
- [ ] Handle merge conflicts with @leebyp's changes from #575

### Eventually
- [ ] Add `allowSingleDayRange` prop
- [ ] Add `selectAllOnFocus` prop
- [ ] Show min/max dates as placeholder on focus in an empty field
- [ ] (e.g.) When selected range is `[<startDate>, <endDate>]` and end field is focused, clicking on `<startDate>` in calendar should _clear_ the start date and _leave_ the end date in place. (Currently, it clears the selected range and then sets the clicked date as a new end date.) Should work symmetrically for start field too.  
- [ ] More robust controlled mode (how should we handle hover events, if at all?)
- [ ] (Refactor) Pull date-range state-change logic into its own `DateRangeSelectionStrategy` class  

### Further out
- [ ] When focused in an input field, allow keyboard incrementing of each of the date, month, or year in isolation (similar to `TimeInput`).

### PR DESCRIPTION
**Pull request by cmslewis**
#### Checklist

- [x] Include tests
- [x] Update documentation

#### Changes proposed in this pull request:

v1 of the `DateRangeInput` is served. 🍲

#### Reviewers should focus on:

No new code here. Just merging all existing work from `feature/date-range-input` into `master`, deconflicting as necessary.

### CODE REVIEW

**Comment by llorca** [comment]
Small bug, probably related to popover and not date range input:
bug

**Comment by cmslewis** [comment]
@llorca can you help with these visual bugs that resulted from the merge conflict deconflicting? It was tricky to get right. Figured you'd want to do a pass yourself anyway. See #586 (Date Range Input - Part 1) for guidance.

**Comment by giladgray** [comment]
the bug where it reopens is definitely a `Popover` thing. It's catching the mouse move over the still-visible (but rapidly shrinking) popover element. @cmslewis we should fix that bug separately, but i'm not sure how we should handle this new prop.

**Comment by giladgray** [comment]
@adidahiya @cmslewis i did the classic merge commit strategy (with a one-two enable-disable) and now chris's 10 parts are scattered throughout history like they've always been there, with one final merge commit at the top. pretty neat.

(i wasn't able to rebase through github due to internal merge conflicts during rebase.)

**Pull request merged**
