### PR TITLE
[icons] feat: new icon "layer-outline"

### PR DESCRIPTION
**Pull request by MichalPrzybys-TomTom**
Changes proposed in this pull request:

New icon: layer outline

16px: layer-outline
20px: layer-outline-20

Clone of #4358 with Circle-CI disabled

### CODE REVIEW

**Comment by adidahiya** [comment]
[here's the docs preview build](https://36173-71939872-gh.circle-artifacts.com/0/packages/docs-app/dist/index.html#icons)

**Review by adidahiya — APPROVED** [review]
LGTM

**Comment by aycai** [comment]
Checking the SVGs in both Sketch and Illustrator for redundancy, the points are not even (see pixel values on the top right). I overlaid a stroked version of the icon and it looks like there are still discrepancies. I'll go ahead and make the adjustments since they are reasonably quick later.

20px values

16px values

**Review by aycai — APPROVED** [review]
@MichalPrzybys-TomTom updated the icons as mentioned earlier, should be good to go now.

**Pull request merged**
