### PR TITLE
[v4] [core] feat(NavbarGroup): use flex layout, support center alignment

### LINKED ISSUE #4468: Navbar.Group Alignment.CENTER is not working
#### Environment

- __Package version(s)__: @blueprintjs/core 3.36.0
- __Browser and OS versions__: Firefox 84.0.1 (64-bit) | Windows 10 build 19041

#### Question
Navbar Alignment functionality doesnt work as intended. 

Navbar Group in the center is being aligned left and filled out to the right, pushing the RIGHT navbar group out of bounds. 

Imgur link to issue: [pic](https://imgur.com/a/61fMNkN)

Codesandbox: https://codesandbox.io/s/blueprint-reactjs-9n6bz

`
<Navbar fixedToTop={true}>

      <Navbar.Group align={Alignment.LEFT}>
          <Button className="bp3-minimal" icon="home" text="Home" />
          <Button className="bp3-minimal" icon="document" text="Files" />
          <Navbar.Divider/>
      </Navbar.Group>

      <Navbar.Group align={Alignment.CENTER}>
          <Navbar.Heading>
              Center
          </Navbar.Heading>
      </Navbar.Group>

      <Navbar.Group align={Alignment.RIGHT}>
          <Navbar.Divider/>
          <Button className="bp3-minimal" icon="user" text="User" />
          <Button className="bp3-minimal" icon="cog" text="Settings" />
      </Navbar.Group>
      
</Navbar>
`

### PR DESCRIPTION
**Pull request by milohansen**
#### Checklist

- [ ] Includes tests
- [x] Update documentation

#### Changes proposed in this pull request:

Added support for `Alignment.CENTER` on `NavbarGroup`. Switched `Navbar` to use flexbox for all alignment.

#### Screenshot

image

### CODE REVIEW

**Comment by vikigenius** [comment]
Is there anything blocking this ? I need to have my search element in the middle of NavBar.

**Comment by adidahiya** [comment]
It's a breaking change to the CSS layout, so I can't merge it yet. I am considering adding this change for v4.0.

**Comment by adidahiya** [comment]
@milohansen can you please update this PR to target the `v4` branch?

**Comment by milohansen** [comment]
@adidahiya I've updated the target. Anything else I can do before this can be merged?

**Comment by adidahiya** [comment]
Just noticed you updated the target after seeing your comment. The branch I'm using now is called `next`, I've updated to target that one. Can you please merge `next` into your feature branch and update the docs example to demonstrate the new feature?

**Comment by milohansen** [comment]
The navbar example has been updated to show all three alignment options.

@adidahiya Is there anything I need to do so the checks are successful?

**Comment by adidahiya** [comment]
@milohansen regarding checks: there was a failing test on the next branch. I have skipped it now, so you can get it passing if you merge next into your branch.

The options in the interactive example are a bit confusing now. What is this supposed to do? This doesn't seem right:




Also, the fixed width example is buggy:

image

[This is the latest docs preview build](https://44091-71939872-gh.circle-artifacts.com/0/packages/docs-app/dist/index.html#core/components/navbar) I'm testing out

**Pull request closed without merging**
