### PR TITLE
Fixing moment to 2.18.1

### PR DESCRIPTION
**Pull request by tnrich**
Trying to fix this issue: https://github.com/palantir/blueprint/issues/1847

Using the advice suggested in:
https://github.com/moment/moment/issues/4216

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/blueprint](https://github.com/palantir/blueprint), @tnrich! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by giladgray** [comment]
@tnrich the linked issue description says "__Edit 3: We believe this is fixed.__" 
Seems like moment 2.19.1 resolves the issue. Do we actually need to do this?

**Comment by giladgray** [comment]
💯  agree with @adidahiya - locking down versions should happen in the consuming app, not in the library.

**Comment by tnrich** [comment]
Awesome! I hadn't heard of yarn resolutions before. I got it to work by adding this to my package.json: 

```
"resolutions": {
    "moment-timezone/moment": "2.18.1"
  },
```

**Pull request closed without merging**
