### PR TITLE
[select] feat(Select2, MultiSelect2): popoverContentProps

### PR DESCRIPTION
**Pull request by bvandrc**
#### Checklist

- [ ] Includes tests
- [ ] Update documentation

#### Changes proposed in this pull request:

allow `popoverContentProps` to be passed to `MultiSelect2` and `Select2`. Allows user to apply props such as `aria-label` or `data-testid` to the popover that is created by these elements.

### CODE REVIEW

**Review by adidahiya — APPROVED** [review]
nice, clean 👍🏽

**Comment by adidahiya** [comment]
I'm adding the same for Suggest2 here: https://github.com/palantir/blueprint/pull/5347

**Comment by bvandrc** [comment]
@adidahiya why was `PopoverContentProps` removed from the props interfaces after this was merged? We need to re-add those

**Comment by adidahiya** [comment]
@bvandercar-vt it's inherited from here in the shared interface: https://github.com/palantir/blueprint/blob/7ea317e054565a23dc4407f7feb5bef4553c195c/packages/select/src/common/selectPopoverProps.ts#L25

**Pull request merged**
