### PR TITLE
MultiSelect: make possible to control the query

### PR DESCRIPTION
**Pull request by alxmiron**
Make possible to control the input query by `tagInputProps.inputProps.value`

### CODE REVIEW

**Comment by alxmiron** [comment]
<h3>MultiSelect: make possible to control the query</h3>

Preview: <strong><a href='https://218-75619030-gh.circle-artifacts.com/0/home/circleci/project/packages/docs-app/dist/index.html' target='_blank'>documentation</a> | <a href='https://218-75619030-gh.circle-artifacts.com/0/home/circleci/project/packages/landing-app/dist/index.html' target='_blank'>landing</a> | <a href='https://218-75619030-gh.circle-artifacts.com/0/home/circleci/project/packages/table-dev-app/dist/index.html' target='_blank'>table</a></strong>

**Comment by alxmiron** [comment]
<h3>MultiSelect: make possible to control the query</h3>

Preview: <strong><a href='https://224-75619030-gh.circle-artifacts.com/0/home/circleci/project/packages/docs-app/dist/index.html' target='_blank'>documentation</a> | <a href='https://224-75619030-gh.circle-artifacts.com/0/home/circleci/project/packages/landing-app/dist/index.html' target='_blank'>landing</a> | <a href='https://224-75619030-gh.circle-artifacts.com/0/home/circleci/project/packages/table-dev-app/dist/index.html' target='_blank'>table</a></strong>

**Comment by giladgray** [comment]
@alxmiron also, please don't amend / force push commits -- it ruins the outdated diffs.

**Comment by alxmiron** [comment]
1. Select, suggest and omnibar support `inputProps.value` correctly.
2. I did not force push. I rerun CI jobs, because sometimes have [problems with Circle CI tracking](https://github.com/palantir/blueprint/pull/2216#issuecomment-371560738)

**Comment by alxmiron** [comment]
Apparently, this is not enough. When I change `inputProps.value`, internal `state.query` does not change. It causes inconsistency - internal `state.query` and input content are different

**Comment by giladgray** [comment]
@alxmiron any update on this PR? would you be able to get it working properly soon?

**Comment by alxmiron** [comment]
This appeared to be not so easy. Sorry I cannot find time to find a solution. Now `resetOnSelect` prop helps me with the problem I faced when created this PR

**Comment by giladgray** [comment]
@alxmiron yeah i know it's a tricky feature. the solution should probably involve `QueryList` in no small way, not _just_ `MultiSelect`. i'm going to close this PR until we have bandwidth to dive deeper. thanks for the attempt!

**Pull request closed without merging**
