### PR TITLE
[table] add editableTextProps to allow adjusting cells during editing

### LINKED ISSUE #2815: EditableCell should expose 'editableTextProps'
#### Environment

- __Package version(s)__: blueprint/table: 3.1.0
- __Browser and OS versions__: NA

#### Feature request

It would be very useful for our use cases (and from looking through the open issues, others as well) if the EditbleCell allowed for EditableText props to be passed down to use functionality such as placeholder, maxLength, multiline, maxLines, minLines, and default value. In complex editable grid scenarios, being able to tap into these existing behaviors of EditableText would be a massive timesaver and removes the need to create completely custom cell components in order to pass a single additional prop to the cell editor.

#### Examples
Support in a cell rendererer: 
```javascript
return (
    <EditableCell 
        key={key} 
        id={id} 
        value={value} 
        // This prop would be great to be able to pass
        editableTextProps={{ 
            maxLength: 255, 
            placeholder: 'Please enter a unique value',
        }}
    />
);
```

### PR DESCRIPTION
**Pull request by alecf**
#### Checklist

- [x] Includes tests
- [ ] Update documentation

#### Changes proposed in this pull request:

Propagating `editableTextProps` as a prop on `EditableCell` so you can control the contents of the cell as you edit. Note that the props are spread into `EditableText` before all the props that `EditableCell` provides.

#### Reviewers should focus on:

Explaining to me how to run tests.. :)

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/blueprint](https://github.com/palantir/blueprint), @alecf! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by alecf** [comment]
I've signed the CLA, I'm not sure when this PR is supposed to be updated..

**Comment by adidahiya** [comment]
@alecf hey, sorry for the delay here... there's a bit of info in the wiki about running tests https://github.com/palantir/blueprint/wiki/Development-practices#running-unit-tests

if you adjust the test script in package.json to add `--browser Chrome` at the end of the `karma` command, it will launch the test runner in a real browser instead of headless Chrome

**Comment by alecf** [comment]
Thanks! I'll make another run at this then

**Comment by alecf** [comment]
@adidahiya sorry for the delay, finally got back to this, got the tests working and everything

**Pull request merged**
