### PR TITLE
[core] feat: darken dark theme colors

### PR DESCRIPTION
**Pull request by adidahiya**
Supersedes https://github.com/palantir/blueprint/pull/6708 and https://github.com/palantir/blueprint/pull/6707

#### Checklist

- [ ] Includes tests
- [x] Update documentation

#### Changes proposed in this pull request:

Update dark theme background colors to be one shade darker for many components based on the following proposal:

image

### CODE REVIEW

**Comment by adidahiya** [comment]
<h3>[core] feat: darken dark theme colors</h3>
Build artifact links for this commit: <strong><a href="https://output.circle-artifacts.com/output/job/a4094471-52ff-4f3f-8cd2-1c1a8ea90e41/artifacts/0/packages/docs-app/dist/index.html">documentation</a> | <a href="https://output.circle-artifacts.com/output/job/a4094471-52ff-4f3f-8cd2-1c1a8ea90e41/artifacts/0/packages/landing-app/dist/index.html">landing</a> | <a href="https://output.circle-artifacts.com/output/job/a4094471-52ff-4f3f-8cd2-1c1a8ea90e41/artifacts/0/packages/table-dev-app/dist/index.html">table</a> | <a href="https://output.circle-artifacts.com/output/job/a4094471-52ff-4f3f-8cd2-1c1a8ea90e41/artifacts/0/packages/demo-app/dist/index.html">demo</a></strong>

<em>This is an automated comment from the deploy-preview CircleCI job.</em>

**Comment by adidahiya** [comment]
<h3>adjust more component colors</h3>
Build artifact links for this commit: <strong><a href="https://output.circle-artifacts.com/output/job/2e8b05cd-fb8a-4b1c-aa1d-0a8d7ee0d657/artifacts/0/packages/docs-app/dist/index.html">documentation</a> | <a href="https://output.circle-artifacts.com/output/job/2e8b05cd-fb8a-4b1c-aa1d-0a8d7ee0d657/artifacts/0/packages/landing-app/dist/index.html">landing</a> | <a href="https://output.circle-artifacts.com/output/job/2e8b05cd-fb8a-4b1c-aa1d-0a8d7ee0d657/artifacts/0/packages/table-dev-app/dist/index.html">table</a> | <a href="https://output.circle-artifacts.com/output/job/2e8b05cd-fb8a-4b1c-aa1d-0a8d7ee0d657/artifacts/0/packages/demo-app/dist/index.html">demo</a></strong>

<em>This is an automated comment from the deploy-preview CircleCI job.</em>

**Comment by adidahiya** [comment]
some components which probably need to be updated for the new colors (or at least their docs examples):

PanelStack

image

ProgressBar

image

Spinner

image

Navbar

image

Switch

image

Table2

image

**Comment by adidahiya** [comment]
notes from sync with @jessperrin:

- many components deserve to be wrapped in a card ("elevated background color") in the docs example so they're not presented on `$black` ("secondary background color")
  - however, some should have "primary background color" (not elevated) since they'll likely be used in a sidebar panel (like Tree)
- let's incorporate the default tag background color change in this PR
- let's add a border to inline `<code>` elements (same as I just added for code blocks)
- consider adding documentation around app layout and which colors (app background, secondary, elevated) apply to which UI elements - possibly fix #4750 
- open questions / specific components to pay attention to
  - editable table with empty space: image

**Comment by adidahiya** [comment]
I incorporated most of the suggestions from my last comment.

Not done yet:

- I didn't update table colors - I think that will require a closer look / more involved change (since it might prompt us to use light borders on tables).
- I did not move the "Dark theme" docs section yet.
- I did not update default tag colors yet.

**Comment by adidahiya** [comment]
<h3>improve appearance and layout of many examples</h3>
Build artifact links for this commit: <strong><a href="https://output.circle-artifacts.com/output/job/be928e00-0634-4a56-abc5-b852bce5c435/artifacts/0/packages/docs-app/dist/index.html">documentation</a> | <a href="https://output.circle-artifacts.com/output/job/be928e00-0634-4a56-abc5-b852bce5c435/artifacts/0/packages/landing-app/dist/index.html">landing</a> | <a href="https://output.circle-artifacts.com/output/job/be928e00-0634-4a56-abc5-b852bce5c435/artifacts/0/packages/table-dev-app/dist/index.html">table</a> | <a href="https://output.circle-artifacts.com/output/job/be928e00-0634-4a56-abc5-b852bce5c435/artifacts/0/packages/demo-app/dist/index.html">demo</a></strong>

<em>This is an automated comment from the deploy-preview CircleCI job.</em>

**Comment by adidahiya** [comment]
<h3>update tag & compound tag colors</h3>
Build artifact links for this commit: <strong><a href="https://output.circle-artifacts.com/output/job/e40e88f7-3378-4af5-94fe-4e3ccc61f13c/artifacts/0/packages/docs-app/dist/index.html">documentation</a> | <a href="https://output.circle-artifacts.com/output/job/e40e88f7-3378-4af5-94fe-4e3ccc61f13c/artifacts/0/packages/landing-app/dist/index.html">landing</a> | <a href="https://output.circle-artifacts.com/output/job/e40e88f7-3378-4af5-94fe-4e3ccc61f13c/artifacts/0/packages/table-dev-app/dist/index.html">table</a> | <a href="https://output.circle-artifacts.com/output/job/e40e88f7-3378-4af5-94fe-4e3ccc61f13c/artifacts/0/packages/demo-app/dist/index.html">demo</a></strong>

<em>This is an automated comment from the deploy-preview CircleCI job.</em>

**Comment by adidahiya** [comment]
I updated tag colors. any more feedback @jessperrin @CPerinet ?

**Comment by adidahiya** [comment]
<h3>render dark background for segmented controls in docs</h3>
Build artifact links for this commit: <strong><a href="https://output.circle-artifacts.com/output/job/f1b36507-7221-437d-aef2-754bcb74efb1/artifacts/0/packages/docs-app/dist/index.html">documentation</a> | <a href="https://output.circle-artifacts.com/output/job/f1b36507-7221-437d-aef2-754bcb74efb1/artifacts/0/packages/landing-app/dist/index.html">landing</a> | <a href="https://output.circle-artifacts.com/output/job/f1b36507-7221-437d-aef2-754bcb74efb1/artifacts/0/packages/table-dev-app/dist/index.html">table</a> | <a href="https://output.circle-artifacts.com/output/job/f1b36507-7221-437d-aef2-754bcb74efb1/artifacts/0/packages/demo-app/dist/index.html">demo</a></strong>

<em>This is an automated comment from the deploy-preview CircleCI job.</em>

**Comment by adidahiya** [comment]
<h3>fix panel stack tests</h3>
Build artifact links for this commit: <strong><a href="https://output.circle-artifacts.com/output/job/acce61b2-3feb-4763-978b-71a8b0e8e72e/artifacts/0/packages/docs-app/dist/index.html">documentation</a> | <a href="https://output.circle-artifacts.com/output/job/acce61b2-3feb-4763-978b-71a8b0e8e72e/artifacts/0/packages/landing-app/dist/index.html">landing</a> | <a href="https://output.circle-artifacts.com/output/job/acce61b2-3feb-4763-978b-71a8b0e8e72e/artifacts/0/packages/table-dev-app/dist/index.html">table</a> | <a href="https://output.circle-artifacts.com/output/job/acce61b2-3feb-4763-978b-71a8b0e8e72e/artifacts/0/packages/demo-app/dist/index.html">demo</a></strong>

<em>This is an automated comment from the deploy-preview CircleCI job.</em>

**Comment by adidahiya** [comment]
Discussed with @ericjeney and we're going to hold off on this PR until the current set of unreleased changes is released as a minor version.

These visual changes will need to be carefully landed in our internal monorepos, since we imagine that there will be many instances of dark theme color variables which may need to be updated to deal with the darker shades in this change.

In the meantime, we should introduce new color aliases to promote a smoother migration from current colors to new ones:

```
$pt-app-secondary-background-color: $white !default;
$pt-dark-app-secondary-background-color: $dark-gray1 !default; // changing to $black in this PR

$pt-app-elevated-background-color: $light-gray4 !default;
$pt-dark-app-elevated-background-color: $dark-gray3 !default; // changing to $dark-gray2 in this PR
```

^ these color aliases should be available in some version of Blueprint _before_ the one with this PR.

**Comment by adidahiya** [comment]
@ericjeney I think we're ready to merge this now, could you give a +1 and merge it at some point this week?

**Comment by ericjeney** [comment]
I think we should hold off on this one until we have a crisper plan for rollout and have a better sense how many hard-coded colors this will affect.

**Review by ggdouglas — APPROVED** [review]

**Pull request merged**
