### PR TITLE
Changed Readme to add showcase link

### PR DESCRIPTION
**Pull request by samarthdave**
### The following is not a bug fix.
- only read me updated

### Changes proposed in this pull request:

Hi there!
I wanted to use a nice UI library for an upcoming project in Electron and since it doesn't need to scale to mobile, this works great!

However, I wanted to see all the components in one place. Here is a site that I built with surge.sh. It would be great if it could be added to the readme. [Here](https://github.com/samarthdave/blueprint_showcase) is the github link to the repo.

Showcase (its pretty simple and a work in progress so please write recommendations):
### [blueprintjs.surge.sh](https://blueprintjs.surge.sh)

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/blueprint](https://github.com/palantir/blueprint), @samarthdave! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by giladgray** [comment]
@samarthdave thank you for taking the time to do this, but unfortunately this is not the kind of experience we want to promote, for a few reasons:

1. the showcase code does not live with the actual library code so they will quickly get out of date.
1. these examples do not conform to our usage guidelines so they encourage bad practices
1. the showcase is not exhaustive -- it only covers a few of the components and none of the "interesting" ones like `Dialog` or `Select`
1. finally, the documentation itself contains all this information and so much more. let's not fracture the ecosystem.

**Comment by samarthdave** [comment]
Sounds good @giladgray . Just curious, do you have any pointers (in regards to #2) for bad/good practices?

Sorry, I'm just getting started with React so I'm a little new to this.
Thanks

**Comment by giladgray** [comment]
@samarthdave we've got some wiki pages for this!
https://github.com/palantir/blueprint/wiki/Coding-guidelines
https://github.com/palantir/blueprint/wiki/Development-practices
https://github.com/palantir/blueprint/wiki/Editor-integration

**Pull request closed without merging**
