### PR TITLE
[Icon] Added explicit typings

### PR DESCRIPTION
**Pull request by anishagg17**
#### Changes proposed in this pull request:

Removed implicitly 'any' type.

### Screenshot
Screenshot 2022-03-08 at 9 10 10 PM

### CODE REVIEW

**Comment by adidahiya** [comment]
@anishagg17 what error or warning were you seeing before this change? What does this actually fix?

**Comment by anishagg17** [comment]
> @anishagg17 what error or warning were you seeing before this change? What does this actually fix?

Hi, @adidahiya I've added screenshot of the issue in the PR description, otherwise you can find the screenshot here https://user-images.githubusercontent.com/43617894/157271939-f8c1567d-4a21-463c-866b-4b38b238b33c.png

**Comment by adidahiya** [comment]
I'm pretty sure you're getting that in your local environment because you haven't built the icons package completely, or your editor hasn't picked it up yet. It's not an error in the build, as you can see that `develop` is passing CI.

**Comment by anishagg17** [comment]
> I'm pretty sure you're getting that in your local environment because you haven't built the icons package completely, or your editor hasn't picked it up yet. It's not an error in the build, as you can see that `develop` is passing CI.

Thanks for the clarification, I'm closing the PR

**Pull request closed without merging**
