### PR TITLE
[core] Fix Toaster regression

### LINKED ISSUE #2232: Toasts position is broken
### Bug report

- __Package version(s)__: 2.0-rc3
- __Browser and OS versions__: Tested on Chrome

#### Steps to reproduce

1. In docs, select a position
2. And click on buttons to show toasts

#### Actual behavior

The chosen position seems not be correctly applied. And break the toast style 😱 

screen shot 2018-03-14 at 11 18 20
screen shot 2018-03-14 at 11 18 27
screen shot 2018-03-14 at 11 18 36

#### Expected behavior

The old behavior :) With correct position.

### PR DESCRIPTION
**Pull request by reiv**

### CODE REVIEW

**Comment by reiv** [comment]
<h3>[core] Fix Toaster regression (#2232)</h3>

Preview: <strong><a href='https://168-120046743-gh.circle-artifacts.com/0/home/circleci/project/packages/docs-app/dist/index.html' target='_blank'>documentation</a> | <a href='https://168-120046743-gh.circle-artifacts.com/0/home/circleci/project/packages/landing-app/dist/index.html' target='_blank'>landing</a> | <a href='https://168-120046743-gh.circle-artifacts.com/0/home/circleci/project/packages/table-dev-app/dist/index.html' target='_blank'>table</a></strong>

**Comment by reiv** [comment]
<h3>Lint</h3>

Preview: <strong><a href='https://174-120046743-gh.circle-artifacts.com/0/home/circleci/project/packages/docs-app/dist/index.html' target='_blank'>documentation</a> | <a href='https://174-120046743-gh.circle-artifacts.com/0/home/circleci/project/packages/landing-app/dist/index.html' target='_blank'>landing</a> | <a href='https://174-120046743-gh.circle-artifacts.com/0/home/circleci/project/packages/table-dev-app/dist/index.html' target='_blank'>table</a></strong>

**Comment by reiv** [comment]
<h3>Lint</h3>

Preview: <strong><a href='https://180-120046743-gh.circle-artifacts.com/0/home/circleci/project/packages/docs-app/dist/index.html' target='_blank'>documentation</a> | <a href='https://180-120046743-gh.circle-artifacts.com/0/home/circleci/project/packages/landing-app/dist/index.html' target='_blank'>landing</a> | <a href='https://180-120046743-gh.circle-artifacts.com/0/home/circleci/project/packages/table-dev-app/dist/index.html' target='_blank'>table</a></strong>

**Comment by giladgray** [comment]
@reiv wooo thanks for this! glad to see we could remove those `> div` selectors

**Pull request merged**
