### PR TITLE
Prepare Release 1.15.0

### PR DESCRIPTION
**Pull request by giladgray**
:fireworks: **Highlights**: top quality bug fixes and some very impressive new `Table` features.

:book: **Latest docs**: [blueprintjs.com/docs](http://blueprintjs.com/docs)

## @blueprintjs/core `1.15.0`
- __Fixed__ `Popover` `useSmartPositioning` does not mutate `defaultProps` for all other popovers on the page #973 
- __Fixed__ `Collapse` overflow styles (follow-up from #938) #976 
- __Fixed__ `Tooltip` `inheritDarkTheme` prop now appears in interface #993 
- __Fixed__ `Tooltip` warns about disabling empty popover only when popover _would_ be shown #1000 
- __Fixed__ set `displayName` correctly on all components (must be `public static`) #982
- __Fixed__ `dark-menu-item` sass mixin argument typo #961 
- __Changed__ most props validation thrown errors to console warnings because they are not error-worthy, merely discouraged #977 #981 
  - a handful of thrown errors remain: invariants that must be met

## @blueprintjs/datetime `1.13.0`
- __NEW__ `DateInput` `popoverProps` prop proxied to `Popover` #560 #974 
- __Fixed__ `DateInput` correctly passes all props to `DateTimePicker` (when `timePrecision` is set) #980 
- __Fixed__ `DateRangeInput` supports full HTMLInputProps on each input #945 
- __Fixed__ `DateRangeInput` spreads all props to `DateRangePicker` #970 
- __Fixed__ set `displayName` correctly on all components (must be `public static`) #982

## @blueprintjs/table `1.12.0`
- 🌟 __NEW__ drag-and-drop column and row reordering! #213 
reordering-v2
  - Column and row reordering can be toggled independently via the following API:
    ```<Table isColumnReorderable={true} onColumnsReordered={myCallback} />```
    ```<Table isRowReorderable={true} onRowsReordered={myCallback} />```
  - `Table` defers to you to reorder your data appropriately. See the documentation for details on `myCallback` implementation; the new `Utils.reorderArray` function can be helpful here.
- 🌟 __NEW__ `table.resizeRowsByTallestCell(columnIndex)` instance method resizes all rows by the tallest visible cell in that column #929 
table-resize-tallest
  - all rows (even those offscreen) are resized to match the desired height (based on content) of the tallest currently visible cell in the given column index
  - to access this instance method you must first get a `ref` to your `<Table>`
- 🌟 __Fixed__ eliminate so many unnecessary re-renders #998
  - added `@PureRender` decorator to all pure table components
  - added custom `shouldComponentUpdate` logic where necessary to handle complex props
  - :fire: `RegionLayer` internal component API accepts pre-computed `regionStyles` instead of `getRegionStyle` function (but you probably won't notice)

## Documentation
- __Fixed__ examples now respond immediately when toggling dark theme #163 
- __Fixed__ remove mentions of calendar button in `DateInput` documentation #966 
- __Fixed__ add a note about i18n support #949

### CODE REVIEW

**Comment by cmslewis** [comment]
**Suggested additions to the `Table` reordering point:**

- 🌟 NEW drag-and-drop column and row reordering! #213 
reordering-v2
  - Column and row reordering can be toggled independently via the following API:
    ```<Table isColumnReorderable={true} onColumnsReordered={myCallback} />```
    ```<Table isRowReorderable={true} onRowsReordered={myCallback} />```
  - `Table` defers to you to reorder your data appropriately. Use `Utils.reorderArray` to help with this.

**Comment by cmslewis** [comment]
nit (not strictly necessary, but reads a little clearer IMO):

> We are tracking noticeable performance issues when scrolling tables that include truncated cells and **are** actively working on a fix.

**Comment by gscshoyru** [comment]
**Suggested edits to resizeRows point**

 - 🌟 NEW table.resizeRowsByTallestCell(columnIndex) instance method resizes all rows by the tallest visible cell in that column. 

apr-18-2017 23-33-38

When creating the table using react, save off a reference to that table using `ref` -- for instance -- `<Table ref={saveTable}/>` `const saveTable = (table: Table) => {
            this.savedTable = table;
        };`

You can then call the instance method to resize all rows in the table (including non-visible ones) to fit the tallest current visible cell in the provided column -- `this.savedTable.resizeRowsByTallestCell(0);` will first determine the largest height among all visible cells in column index 0 big enough to fit all their content, then resize every single row in the table to that largest height. 

This feature most useful with word-wrapped cells, and cells that contain a lot of vertical data that you might want to display all at once without requiring users to resize them all themselves.

**Comment by giladgray** [comment]
removed performance warning cuz we haven't confirmed in prod mode react.

**Comment by cmslewis** [comment]
Huh, scrolling perf is actually much better in this preview than we observed yesterday, yet it's not in prod mode.

**Pull request merged**
