### PR TITLE
Prepare Release 1.31.0

### PR DESCRIPTION
**Pull request by cmslewis**
:fireworks: **Highlights**: initial React 16 support, `Table` empty states, `Table` size-syncing fixes, `Table` no longer swallows page scrolls, ⚠️  different `TruncatedFormat` defaults 

:book: **Latest docs**: [blueprintjs.com/docs](http://blueprintjs.com/docs)

### 💎 New features
- 🌟  #1660 Allow React 16 as Blueprint `peerDependency`.
  - all components render successfully but please report any deeper issues you encounter.
- #1677 Added __eleven__ new icons:
    - `pt-icon-compass`, `pt-icon-console`, `pt-icon-form`, `pt-icon-series-add`, `pt-icon-series-configuration`, `pt-icon-series-derived`, `pt-icon-series-filtered`, `pt-icon-series-search`, `pt-icon-taxi`, `pt-icon-train`, `pt-icon-walk`

### 🐛 Bug fixes
- #1672 `Submenu` popovers now position themselves properly on IE.
- #1644 `Popover` no longer throws an error when shallow-mounted in a test environment. (🎩 @tobilen)
- #1492 `Tabs2` now hides the selected-tab indicator when the selected tab is removed. (🎩 @franciscofabian)

### 🐛 Bug fixes
- 🌟  #1663 `Table` empty states are now both sane and beautiful.
    - Column-header borders are no longer missing.
image image
    - Column header no longer collapses in size when `numCols === 0`
image
    - Selections are cleared and selecting is disabled when `numRows === 0` and/or `numCols === 0`

- 🌟  #1663 `Table` now resizes elements properly when the column header's size changes.

- 🌟  #1674 `Table` now allows scrolling the page when the cursor is within the table.

- #1637 `Table` no longer allows inertial scroll beyond the last row or column.
- #1637 `Table` now doesn't stick _as much_ when you try to scroll slowly leftward/upward from the last column/row.
- #1632 `Table` now properly resizes frozen columns on double-click while the table is scrolled.
    - Before, double-clicking to resize a frozen column would sometimes erroneously collapse the column to nearly zero width.
- #1653 `Table` no longer throws an error when scrolling a grid whose `width` or `height` is smaller than the scroll area.
- #1673 `EditableCell` text input now fills the entire vertical space of the cell.
- #1651 `EditableCell` no longer overwrites new values with old values when typing very quickly after focusing in the field.

### 🔄 Changed

- ⚠️  #1656 `TruncatedFormat`'s `detectTruncation` prop is now `false` by default, and `truncationLength` is set to `2000`.
    - `detectTruncation` noticeably degrades performance when enabled, so we decided it was better to make it opt-in.
    - Now, when using `TruncatedFormat` with default settings, only cells with at least `2,000` characters will show a `···` icon and an accompanying `Popover` on click.
    - This should drastically reduce the work this component does on scroll, leading to _much_ better rendering performance for cells with less than `2,000` characters of content.
    - __To undo this change, set `detectTruncation=true` and `truncationLength=80` in all of your `TruncatedFormat` usages, or modify `TruncatedFormat.defaultProps` directly:__
        ```tsx
        // changes values for _every_ instance without modifying render functions
        TruncatedFormat.defaultProps.detectTruncation = true;
        TruncatedFormat.defaultProps.maxLength = 80;
        ```
- #1679 `Table` now always disables batch-rendering for header cells.
    - This fixes a race condition where the row header would resize itself incorrectly because some header cells hadn't finished rendering yet.

## Documentation

- #1662 `Checkbox`/`Radio`/`Switch` examples' "View on GitHub" links are now fixed. (🎩 @zfranklyn)
- #1654 `Table` fixed an incorrectly stated default value for `TruncatedFormat`'s `showPopover` prop.
- #1666 `Table` added Regions/`IRegion` documentation

### CODE REVIEW

**Comment by cmslewis** [comment]
Will wait for another +1 or two before merging.

**Comment by giladgray** [comment]
I tweaked React 16 language.

There's another (rather literal) way to change `Table` prop defaults, though I'm not sure we want to share it:

```ts
// changes values for _every_ instance without modifying render functions
Table.defaultProps.detectTruncation = true;
Table.defaultProps.maxLength = 80;
```

**Comment by sesm** [comment]
@cmslewis did Blueprint team consider publishing alpha/beta builds on NPM?
Currently it's non-trivial to test unreleased version, because of NPMs poor support for monorepos (https://github.com/npm/npm/issues/2974)

**Comment by cmslewis** [comment]
@sesm I don't think the team has discussed it, no. But we release pretty much every week and frankly tend to merge most of our outstanding PRs right before the "deadline," so (1) the alpha/beta release likely wouldn't be representative of the final release, (2) most features would be on an alpha/beta release for just a few hours before we cut the real thing, (3) and the cost of waiting a few days before seeing the official release doesn't seem too big a burden.

@giladgray @adidahiya @llorca can chime in if they feel differently.

**Comment by sesm** [comment]
@cmslewis thank you for explanation, sounds reasonable.

**Comment by adidahiya** [comment]
@cmslewis it's be pretty easy to set up "snapshot" builds on commits that merge into develop; this is something I want to do. We would publish them to the `next` dist-tag on NPM and version them with a string containing the number of commits since last release and the first 7 characters of the commit hash.

Quotes around "snapshot" because the NPM releases won't be deleted after some retention window -- they'll always be there.

**Pull request merged**
