### PR TITLE
InputGroup -> Input

### LINKED ISSUE #1147: Rename InputGroup to Input
There's an opportunity to simplify this naming by merging input and input groups together into `Input` or `TextInput`. They're really the same thing. Thoughts?

### PR DESCRIPTION
**Pull request by tgreenwatts**
#### Checklist

Question about what to do with https://github.com/palantir/blueprint/blob/tgreen/inputGroup/packages/core/src/components/forms/input-group.md and https://github.com/palantir/blueprint/blob/tgreen/inputGroup/packages/core/src/components/forms/_input-group.scss

### CODE REVIEW

**Comment by tgreenwatts** [comment]
Also it still says "Text input group" - but it doesn't really make sense as just "Text input" since there already is a section for that 

image

**Comment by adidahiya** [comment]
wait this is weird, I'm not sure why we're doing this. it doesn't render an `<input>`, it renders a `<div>`. I thought InputGroup was fine

**Comment by llorca** [comment]
it's more elaborated than just an input indeed, it's made with a div wrapping an input. but functionally, it's still very much like `<input>`, even though the implementation details are different

**Comment by llorca** [comment]
This PR is a little tricky because at the moment with have both inputs and input groups. Inputs are pretty useless because all their features are covered by input groups, and input groups do much more as well

**Comment by giladgray** [comment]
i think we should stick with `InputGroup` for now as it's a finicky break and the no-conflict name with `input` is a good thing.

**Pull request closed without merging**
