### PR TITLE
Maximize Dialog to full viewport width and height

### PR DESCRIPTION
**Pull request by cnrudd**
#### Checklist

- [x] [Enable CircleCI for your fork](https://circleci.com/add-projects)
- [x] Include tests
- [x] Update documentation

#### Changes proposed in this pull request:

This adds a prop to the dialog button: 
`isMaximizeButtonShown`
that controls the display of a maximize/minimize button placed in the dialog header.

The default value of the prop is `false` - no maximize button shown.

Maximizing a dialog expands it to fill the full width and height of the viewport by adding the class `{$ns}-dialog-maximized` to the dialog component's div.
Once the dialog is maximized, the button toggles to show a minimize icon, and the dialog can be brought back down to its original size.

The display of the button follows the logic used for the Close Button.
If the `title` is not defined, the isMaximizeButtonShown prop is ignored.
Also, if `usePortal` is false, the isMaximizeButtonShown prop is ignored, because maximizing a dialog inside a smaller container that is not the viewport can yield less predictable outcomes and  is a less frequent use case.

This change required that state.isMaximized be added to the dialog component.

In the apps we are building, we have many use cases in which a larger view of dialog content would be helpful.  I am aware of the decisions taken around resizable and draggable dialogs (https://github.com/palantir/blueprint/issues/336).  

In most of the use cases I come across, the ability to maximize a dialog quickly (rather than resize by edge dragging) satisfies the need to 'resize' the dialog.  I thought this non-breaking, no-dependency change would be a good, small feature to add to the component to answer most needs for a resizable dialog.

#### Reviewers should focus on:

The usual: that this new feature does not break any existing features, and that it performs well.

#### Screenshot

screen shot 2018-04-30 at 2 13 39 pm
screen shot 2018-04-30 at 2 10 55 pm

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/blueprint](https://github.com/palantir/blueprint), @cnrudd! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by cnrudd** [comment]
@palantirtech Exhi has emailed in the signed corporate CLA.

**Comment by llorca** [comment]
thanks for the contribution, @cnrudd. this is clean and thorough!

Although this is a cool interaction, I'm not convinced that it makes sense for Blueprint to implement this feature as a top-level API. Let me lay out a few concerns, then we can discuss with the rest of the team:
- it's quite trivial -- the core of the feature is a boolean prop that changes 3 lines of CSS. Seems that it could easily be implemented at the app level, and if not, we may want to address that part.
- it's an uncommon, specific feature for a specific component. Blueprint tries to avoid implementing these things as much as possible (though it's not perfect). I'd be curious to hear thoughts on the rationale for integrating this feature at the Blueprint level, as opposed to the app level.

Blueprint has to carefully choose the code and features it maintains, and basically I'm not sure we can afford enlarging the API surface for small specific features like these (unless they're truly generic across the system), considering the size of the project and small number of maintainers.

**Comment by giladgray** [comment]
closing this PR due to comments above and merge conflicts due to bad initial branching.

@cnrudd i'd love to see a new PR to add support for custom title actions.

**Comment by cnrudd** [comment]
@giladgray I agree that a titleActions component would make a lot of sense here, but I can’t commit to finding the time for working on that.  I will certainly check in again if I can.

**Comment by amcclain** [comment]
Hi - I work with Colin at our small software consultancy, where we have recently started using Blueprint to help power our React development.  Wanted to say thanks for reviewing this P/R - we'll take another tack on this particular feature, but we really appreciate the library and will look for other ways for our team to contribute in the future.   Best regards - Anselm

**Comment by giladgray** [comment]
@amcclain awesome! So glad to hear Blueprint is working well for you! I'm happy to continue reviewing submissions, and feel free to ask questions or start discussions in issues 🌴

**Pull request closed without merging**
