### PR TITLE
[core] fix(ControlGroup): normalize fill style

### LINKED ISSUE #4213: NumericInput fill prop doesn't work
discovered while testing https://github.com/palantir/blueprint/pull/4211

#### Environment

- __Package version(s)__: develop & 3.29.0
- __Operating System__: macOS
- __Browser name and version__: Firefox

#### Steps to reproduce

1. Enable fill option in NumericInput docs

#### Actual behavior

image

#### Expected behavior

control group should be full width

### PR DESCRIPTION
**Pull request by ejose19**
#### Changes proposed in this pull request:

Normalize fill for ControlGroup like the rest of the components, so it works as intended.

### CODE REVIEW

**Comment by ejose19** [comment]
Maybe an edit to https://blueprintjs.com/docs/#core/components/control-group.flex-layout is required, as it's stating:
>Enable the fill prop on a control group to make all controls expand equally to fill the available space.

However, that was never the case as seen in the docs, using fill on ControlGroup distributes the space proportionally to the original child sizes. True equality can be obtained if all the childs also have fill set.

**Review by adidahiya — APPROVED** [review]

**Comment by adidahiya** [comment]
made a documentation tweak here: https://github.com/palantir/blueprint/commit/13ff0ae9ec122a9c284df9efff70e8073a0c9e2c

**Comment by ejose19** [comment]
@adidahiya Ok that change is good, but shouldn't the other line be modified too?

from this:
> Enable the fill prop on a control group to make all controls expand equally to fill the available space.

to this:
> Enable the fill prop on a control group to make all controls fill the available space expanding proportionally to their original sizes.

**Comment by adidahiya** [comment]
I think the existing documentation can be interpreted as correct; "expand equally" (although somewhat ambiguous) can mean that they grow proportionally, i.e. `flex-grow: 1` for all elements

**Pull request merged**
